(()=>{
'use strict';
const WORD_KEY='vivid-reading-test-words-v1';
const STOP=new Set('the a an and or but if to of in on at by for from with as is are was were be been being it its this that these those do does did has have had can could may might will would should about into over under after before than then which who whom whose where when why how what your you they them their we our he she his her not no yes true false given passage reading question questions statement paragraph according following choose correct write answer box boxes'.split(' '));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clean=s=>String(s??'').replace(/\s+/g,' ').trim();
const norm=s=>clean(s).toLowerCase().normalize('NFKD').replace(/[’‘]/g,"'").replace(/[^a-z0-9' -]+/g,' ');
const toks=s=>[...new Set(norm(s).split(/\s+/).filter(x=>x.length>2&&!STOP.has(x)))];
const sentences=s=>clean(s).split(/(?<=[.!?])\s+(?=[A-Z0-9“"'])/).map(clean).filter(x=>x.length>25);
function toast(msg){let el=document.querySelector('.vivid-word-toast');if(!el){el=document.createElement('div');el.className='vivid-word-toast';document.body.appendChild(el)}el.textContent=msg;el.classList.add('show');clearTimeout(el._t);el._t=setTimeout(()=>el.classList.remove('show'),1800)}
function loadWords(){try{const x=JSON.parse(localStorage.getItem(WORD_KEY)||'[]');return Array.isArray(x)?x:[]}catch{return[]}}
function saveWords(x){try{localStorage.setItem(WORD_KEY,JSON.stringify(x.slice(-500)))}catch{}}
function addWord(term){term=clean(term).replace(/^[\s.,;:!?"“”'‘’()[\]{}]+|[\s.,;:!?"“”'‘’()[\]{}]+$/g,'');if(!term||term.length>120)return false;const list=loadWords();if(list.some(x=>norm(x.word)===norm(term))){toast('Bu so‘z/ibora avval qo‘shilgan.');return false}list.push({word:term,test:document.title.replace(/\s*[—|-].*VIVID IELTS.*$/i,'').trim(),addedAt:new Date().toISOString()});saveWords(list);updateDock();toast('Words’ga qo‘shildi ✓');return true}
function pdfAscii(s){return String(s).normalize('NFKD').replace(/[^\x20-\x7E]/g,c=>({'’':"'",'‘':"'",'“':'"','”':'"','–':'-','—':'-'}[c]||'?')).replace(/([\\()])/g,'\\$1')}
function wrapLine(s,max=78){const words=pdfAscii(s).split(/\s+/);const out=[];let line='';for(const w of words){if(!line){line=w;continue}if((line+' '+w).length<=max)line+=' '+w;else{out.push(line);line=w}}if(line)out.push(line);return out}
function makePDF(lines){const per=46,pages=[];for(let i=0;i<lines.length;i+=per)pages.push(lines.slice(i,i+per));if(!pages.length)pages.push(['No saved words.']);const objs=[];const add=s=>{objs.push(s);return objs.length};const font=add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>');const pageIds=[];const contentIds=[];for(const pageLines of pages){let y=800;const ops=['BT','/F1 15 Tf',`50 ${y} Td`,'(VIVID IELTS - Reading Test Words) Tj','/F1 11 Tf'];y-=30;for(const line of pageLines){ops.push(`0 -18 Td (${pdfAscii(line)}) Tj`);y-=18}ops.push('ET');const stream=ops.join('\n');const cid=add(`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`);contentIds.push(cid);pageIds.push(null)}const pagesObjIndex=objs.length+1+pages.length;for(let i=0;i<pages.length;i++){pageIds[i]=add(`<< /Type /Page /Parent ${pagesObjIndex} 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 ${font} 0 R >> >> /Contents ${contentIds[i]} 0 R >>`)}const pagesObj=add(`<< /Type /Pages /Kids [${pageIds.map(x=>x+' 0 R').join(' ')}] /Count ${pageIds.length} >>`);const catalog=add(`<< /Type /Catalog /Pages ${pagesObj} 0 R >>`);let pdf='%PDF-1.4\n';const offsets=[0];objs.forEach((o,i)=>{offsets[i+1]=pdf.length;pdf+=`${i+1} 0 obj\n${o}\nendobj\n`});const xref=pdf.length;pdf+=`xref\n0 ${objs.length+1}\n0000000000 65535 f \n`;for(let i=1;i<=objs.length;i++)pdf+=String(offsets[i]).padStart(10,'0')+' 00000 n \n';pdf+=`trailer\n<< /Size ${objs.length+1} /Root ${catalog} 0 R >>\nstartxref\n${xref}\n%%EOF`;return new Blob([pdf],{type:'application/pdf'})}
function downloadWords(){const list=loadWords();if(!list.length){toast('Avval testdan so‘z/ibora qo‘shing.');return}const lines=[];list.forEach((x,i)=>{const item=`${i+1}. ${x.word}${x.test?'  ['+x.test+']':''}`;lines.push(...wrapLine(item))});const url=URL.createObjectURL(makePDF(lines));const a=document.createElement('a');a.href=url;a.download=`vivid-ielts-reading-words-${new Date().toISOString().slice(0,10)}.pdf`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),15000);toast('PDF tayyor ✓')}
function submitted(){return document.documentElement.dataset.vividReadingSubmitted==='1'||document.body.classList.contains('vivid-reading-submitted')}
function setSubmitted(){document.documentElement.dataset.vividReadingSubmitted='1';document.body.classList.add('vivid-reading-submitted');updateDock()}
function updateDock(){let dock=document.querySelector('.vivid-post-submit-dock');if(!dock){dock=document.createElement('div');dock.className='vivid-post-submit-dock';dock.innerHTML='<span class="count"></span><small>Matndan so‘z/ibora belgilang → Words’ga qo‘shish</small><button class="primary pdf" type="button">PDF yuklash</button>';dock.querySelector('.pdf').addEventListener('click',downloadWords);document.body.appendChild(dock)}dock.querySelector('.count').textContent=`Words: ${loadWords().length}`;dock.classList.toggle('show',submitted())}
function topBack(){if(location.pathname.endsWith('/reading.html')||location.pathname.endsWith('/index.html'))return;const existing=document.querySelector('.vivid-reading-top-back');if(existing)return;const top=document.querySelector('.topbar,.header,.exam-header,header');if(!top)return;const href=new URL('/index.html',location.href);href.hash='readingtests';const a=document.createElement('a');a.className='vivid-reading-top-back';a.href=href.href;a.innerHTML='← <b>VIVID IELTS</b>';if(top.querySelector('.brand')){const b=top.querySelector('.brand');b.innerHTML='← <strong>VIVID <em>IELTS</em></strong>';b.href=href.href;b.classList.add('vivid-reading-top-back');return}top.insertBefore(a,top.firstChild)}
function passageRoot(){return document.querySelector('#passagePane,.passage-pane,.pane.left,.passage,.passage-content,.reading-text,.passage-text')}
function allReadingRoot(){return document.querySelector('.panes,.main,#app,.exam-container')||document.body}
function optionText(q,correct){const c=String(correct??'').split('|')[0].trim();const selectors=[`input[name="q${q}"][value="${CSS.escape(c)}"]`,`input[name="answer-q${q}"][value="${CSS.escape(c)}"]`,`#q${q}`];for(const sel of selectors){const el=document.querySelector(sel);if(!el)continue;if(el.tagName==='SELECT'){const opt=[...el.options].find(o=>clean(o.value)===c);if(opt)return clean(opt.textContent)}const lab=el.closest('label');if(lab)return clean(lab.textContent)}return''}
function qText(q){const candidates=[`[data-question-anchor="${q}"]`,`[data-q="${q}"]`,`#q${q}`,`[name="q${q}"]`,`[name="answer-q${q}"]`];for(const sel of candidates){const el=document.querySelector(sel);if(!el)continue;const box=el.closest('.question-row,.qblock,.q-block,.question,.mcq-question,.tf-question,.matching-question,.yn-row,p,li,tr')||el.parentElement;let text=clean(box?.textContent||'');text=text.replace(new RegExp(`^${q}\\s*[.)-]?\\s*`),'');if(text.length>10)return text.slice(0,800)}return`Question ${q}`}
function paragraphByLetter(letter,root){if(!root||!/^[A-I]$/i.test(letter))return'';letter=letter.toUpperCase();const blocks=[...root.querySelectorAll('p')];for(let i=0;i<blocks.length;i++){const t=clean(blocks[i].textContent);if(new RegExp(`^${letter}(?:\\s|\\.|:)`).test(t))return t.replace(new RegExp(`^${letter}(?:\\s|\\.|:)\\s*`),'')}return''}
function evidence(question,correct){const root=passageRoot();if(!root)return'';const answer=clean(correct).split('|')[0];const opt=optionText((question.match(/^Question (\d+)/)||[])[1]||'',answer);const query=[question,opt,/^(TRUE|FALSE|YES|NO|NOT GIVEN)$/i.test(answer)?'':answer].join(' ');if(/^[A-I]$/i.test(answer)){const para=paragraphByLetter(answer,root);if(para)return para.slice(0,420)}const txt=clean(root.innerText||root.textContent);const ss=sentences(txt);const qt=toks(query);let best='',bestScore=-1;for(const s of ss){const st=new Set(toks(s));let score=0;for(const t of qt)if(st.has(t))score+=t.length>7?3:1;const an=norm(answer);if(an&&an.length>3&&norm(s).includes(an))score+=8;if(score>bestScore){bestScore=score;best=s}}return bestScore>0?best.slice(0,460):''}
function explanationText(q,correct,question){const c=clean(correct).replaceAll('|',' / ');const ev=evidence(question,c);let lead='';if(/^(TRUE|YES)$/i.test(c))lead='Matndagi ma’lumot savoldagi fikrni bevosita qo‘llab-quvvatlaydi.';else if(/^(FALSE|NO)$/i.test(c))lead='Savoldagi fikr matndagi ma’lumotga zid yoki undan boshqacha.';else if(/^NOT GIVEN$/i.test(c))lead='Matnda bu fikrni aniq tasdiqlash yoki rad etish uchun yetarli ma’lumot berilmagan.';else lead='Savoldagi ma’no va matndagi tegishli qism shu javobga mos keladi.';return {lead,ev}}
function buildExplanationNode(q,correct,given){const question=qText(q);const {lead,ev}=explanationText(q,correct,question);const d=document.createElement('details');d.className='vivid-explanation';d.innerHTML=`<summary>Q${q} · <span class="answer">${esc(clean(correct).replaceAll('|',' / '))}</span></summary><div class="body"><div><b>Izoh:</b> ${esc(lead)}</div><div class="question-line"><b>Savol:</b> ${esc(question)}</div>${ev?`<div class="evidence"><b>Passage dalili:</b> “${esc(ev)}”</div>`:`<div class="evidence warn">Bu savol uchun avtomatik aniq dalil jumlasi ajratilmadi; to‘g‘ri javob yuqoridagi answer key asosida ko‘rsatildi.</div>`}${given!=null?`<div class="question-line"><b>Sizning javobingiz:</b> ${esc(given||'—')}</div>`:''}</div>`;return d}
function addResultTools(container){if(!container||container.querySelector('.vivid-reading-result-tools'))return;const bar=document.createElement('div');bar.className='vivid-reading-result-tools';bar.innerHTML='<button type="button" class="primary review">Matnga qaytish · Words qo‘shish</button><button type="button" class="pdf">Words PDF</button>';bar.querySelector('.pdf').onclick=downloadWords;bar.querySelector('.review').onclick=()=>{const ov=container.closest('.overlay,#overlay,.results-overlay');if(ov){ov.classList.remove('visible');ov.classList.add('hidden')}else document.querySelector('.overlay.visible')?.classList.remove('visible')};container.insertBefore(bar,container.querySelector('.vivid-explanations')||container.lastChild)}
function attachExplanationsFromRows(rows,container){if(!rows?.length||!container)return;if(!container.querySelector('.vivid-explanations')){const wrap=document.createElement('section');wrap.className='vivid-explanations';wrap.innerHTML='<h3>Barcha savollar izohi</h3><p class="intro">Har bir savolda to‘g‘ri javob va passage’dan eng yaqin dalil ko‘rsatiladi.</p>';for(const r of rows)wrap.appendChild(buildExplanationNode(r.q,r.correct??r.key,r.given));container.appendChild(wrap)}addResultTools(container);setSubmitted()}
function htmlText(html){const d=document.createElement('div');d.innerHTML=html||'';return clean(d.textContent||'')}
function importedQuestion(part,q){
  if(Array.isArray(part?.sections)){
    for(const sec of part.sections){const item=(sec.items||[]).find(x=>Number(x.id)===Number(q));if(item){let text=clean(item.label||sec.prompt||sec.title||`Question ${q}`);if(sec.type==='matching-headings'){const idx=(sec.items||[]).findIndex(x=>Number(x.id)===Number(q));const letter=(part.headingSlots||[])[idx]?.letter;if(letter)text=`Paragraph ${letter}: ${text}`;}return text}}
  }
  const box=document.createElement('div');box.innerHTML=part?.questions||'';
  const el=box.querySelector(`#q${q},[name="q${q}"],[name="answer-q${q}"],[data-q="${q}"]`);
  if(el){const wrap=el.closest('.tf-question,.mcq-question,.matching-question,.question-row,p,li,tr,.question')||el.parentElement;let text=clean(wrap?.textContent||'');text=text.replace(new RegExp(`^${q}\\s*[.)-]?\\s*`),'');return text.slice(0,850)}
  return `Question ${q}`;
}
function importedOptionText(part,q,correct){const c=clean(correct).split('|')[0];const box=document.createElement('div');box.innerHTML=part?.questions||'';const el=box.querySelector(`input[name="q${q}"][value="${CSS.escape(c)}"],input[name="answer-q${q}"][value="${CSS.escape(c)}"],#q${q}`);if(!el)return'';if(el.tagName==='SELECT'){const opt=[...el.options].find(o=>clean(o.value)===c);return clean(opt?.textContent||'')}return clean(el.closest('label')?.textContent||'')}
function importedParagraph(letter,html){if(!/^[A-I]$/i.test(letter||''))return'';const d=document.createElement('div');d.innerHTML=html||'';for(const p of d.querySelectorAll('p')){const t=clean(p.textContent);if(new RegExp(`^${letter}(?:\\s|\\.|:)`,'i').test(t))return t.replace(new RegExp(`^${letter}(?:\\s|\\.|:)\\s*`,'i'),'')}return''}
function evidenceText(question,correct,passage,option='',passageHtml=''){
  const answer=clean(correct).split('|')[0];const paraLetter=(question.match(/Paragraph\s+([A-I])/i)||[])[1];
  if(paraLetter){const x=importedParagraph(paraLetter,passageHtml);if(x)return x.slice(0,460)}
  if(/^[A-I]$/i.test(answer)){const x=importedParagraph(answer,passageHtml);if(x)return x.slice(0,460)}
  const query=[question,option,/^(TRUE|FALSE|YES|NO|NOT GIVEN)$/i.test(answer)?'':answer].join(' '),ss=sentences(passage),qt=toks(query);let best='',bestScore=-1;
  for(const stxt of ss){const set=new Set(toks(stxt));let score=0;for(const t of qt)if(set.has(t))score+=t.length>7?3:1;if(answer.length>3&&norm(stxt).includes(norm(answer)))score+=8;if(score>bestScore){bestScore=score;best=stxt}}
  return bestScore>0?best.slice(0,460):'';
}
function buildImportedExplanationNode(r,data,parts){const part=(parts||data?.parts||[]).find(p=>r.q>=p.fromQuestion&&r.q<=p.toQuestion)||{};const correct=r.key??r.correct;const question=importedQuestion(part,r.q);const option=importedOptionText(part,r.q,clean(correct).split('|')[0]);const passage=htmlText(part.passage);const ev=evidenceText(question,correct,passage,option,part.passage||'');const c=clean(correct).replaceAll('|',' / ');let lead='';if(/^(TRUE|YES)$/i.test(c))lead='Matndagi ma’lumot savoldagi fikrni bevosita qo‘llab-quvvatlaydi.';else if(/^(FALSE|NO)$/i.test(c))lead='Savoldagi fikr matndagi ma’lumotga zid yoki undan boshqacha.';else if(/^NOT GIVEN$/i.test(c))lead='Matnda bu fikrni aniq tasdiqlash yoki rad etish uchun yetarli ma’lumot berilmagan.';else lead='Savoldagi ma’no va passage’dagi tegishli qism shu javobga mos keladi.';const d=document.createElement('details');d.className='vivid-explanation';d.innerHTML=`<summary>Q${r.q} · <span class="answer">${esc(c)}</span></summary><div class="body"><div><b>Izoh:</b> ${esc(lead)}</div><div class="question-line"><b>Savol:</b> ${esc(question)}</div>${option&&option!==c?`<div class="question-line"><b>Javob varianti:</b> ${esc(option)}</div>`:''}${ev?`<div class="evidence"><b>Passage dalili:</b> “${esc(ev)}”</div>`:`<div class="evidence warn">Bu savol uchun avtomatik aniq dalil jumlasi ajratilmadi; to‘g‘ri javob answer key asosida ko‘rsatildi.</div>`}<div class="question-line"><b>Sizning javobingiz:</b> ${esc(r.given||'—')}</div></div>`;return d}
function attachImportedExplanations(rows,data,parts,container){if(!rows?.length||!container)return;if(!container.querySelector('.vivid-explanations')){const wrap=document.createElement('section');wrap.className='vivid-explanations';wrap.innerHTML='<h3>Barcha savollar izohi</h3><p class="intro">Har bir savolda to‘g‘ri javob va passage’dan tegishli dalil ko‘rsatiladi.</p>';for(const r of rows)wrap.appendChild(buildImportedExplanationNode(r,data,parts));container.appendChild(wrap)}addResultTools(container);setSubmitted()}
function parseResultsTable(){const table=document.querySelector('.results-table');if(!table)return null;const rows=[];for(const tr of table.querySelectorAll('tbody tr')){const td=tr.querySelectorAll('td');if(td.length<3)continue;const q=Number(clean(td[0].textContent).match(/\d+/)?.[0]);if(!q)continue;rows.push({q,given:clean(td[1].textContent),correct:clean(td[2].textContent).replace(/^✓\s*/, '')})}return rows.length?rows:null}
function detectResult(){const rows=parseResultsTable();if(rows){const container=document.querySelector('.modal,.result-card,.overlay.visible,#resultsModal,.results-modal')||document.body;attachExplanationsFromRows(rows,container);return}const resultRows=document.querySelector('#resultRows');if(resultRows&&resultRows.children.length&&resultRows.closest('.overlay:not(.hidden),.modal')){const rows2=[];for(const el of resultRows.children){const spans=el.querySelectorAll('span');const q=Number(el.querySelector('strong')?.textContent);if(q)rows2.push({q,given:clean(spans[0]?.textContent||''),correct:clean(spans[1]?.textContent||'').replace(/^✓\s*/,'')})}if(rows2.length)attachExplanationsFromRows(rows2,resultRows.parentElement)}}
let popup;
function ensurePopup(){if(popup)return popup;popup=document.createElement('div');popup.className='vivid-selection-popup';popup.innerHTML='<button class="hl" type="button">🖍 Highlight</button><button class="add-word" type="button">＋ Words</button><button class="close" type="button">×</button>';document.body.appendChild(popup);popup.querySelector('.close').onclick=()=>popup.classList.remove('show');return popup}
function selectionAllowed(range){const root=allReadingRoot();if(!root.contains(range.commonAncestorContainer))return false;const node=range.commonAncestorContainer.nodeType===1?range.commonAncestorContainer:range.commonAncestorContainer.parentElement;if(node?.closest('input,textarea,select,button,.topbar,.footer,.vivid-selection-popup,.modal,.overlay,.notes-panel'))return false;return true}
function handleSelection(ev){const sel=window.getSelection();if(!sel||sel.rangeCount===0)return;const text=clean(sel.toString());if(!text||text.length>180)return;const range=sel.getRangeAt(0);if(!selectionAllowed(range))return;const ownExisting=!!document.querySelector('.highlight-popup');if(ownExisting&&!submitted()&&!location.pathname.includes('/imported-reading/'))return;const p=ensurePopup();const rect=range.getBoundingClientRect();p.style.left=Math.max(8,Math.min(innerWidth-p.offsetWidth-8,rect.left))+'px';p.style.top=Math.max(8,rect.top-48)+'px';p.querySelector('.add-word').style.display=submitted()?'inline-flex':'none';p.classList.add('show');const cloned=range.cloneRange();p.querySelector('.hl').onclick=()=>{try{const mark=document.createElement('mark');mark.className='vivid-user-highlight';cloned.surroundContents(mark)}catch{}sel.removeAllRanges();p.classList.remove('show')};p.querySelector('.add-word').onclick=()=>{addWord(text);sel.removeAllRanges();p.classList.remove('show')};if(submitted()){ev.stopImmediatePropagation?.()}}
window.addEventListener('vivid-reading-submitted',e=>{setSubmitted();const d=e.detail||{};const container=document.querySelector('#resultRows')?.parentElement||document.querySelector('.result-card,.modal')||document.body;if(Array.isArray(d.rows))attachImportedExplanations(d.rows,d.data,d.parts,container)});
document.addEventListener('mouseup',handleSelection,true);
document.addEventListener('pointerdown',e=>{if(popup&&!e.target.closest('.vivid-selection-popup'))popup.classList.remove('show')},true);
const observer=new MutationObserver(()=>detectResult());observer.observe(document.documentElement,{subtree:true,childList:true,attributes:true,attributeFilter:['class','style','open']});
document.addEventListener('click',e=>{const b=e.target.closest('button,input[type=button],input[type=submit]');if(!b)return;const t=clean(b.textContent||b.value).toLowerCase();if(/submit|check answers|see results|finish|yakun|tekshirish/.test(t))setTimeout(detectResult,80)},true);
document.addEventListener('DOMContentLoaded',()=>{topBack();updateDock();setTimeout(detectResult,200)});
window.VividReadingTools={setSubmitted,attachExplanationsFromRows,addWord,downloadWords,detectResult};
})();
