(() => {
'use strict';
const STORAGE='vivid-tenses-progress-v1';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s||'').toLowerCase().replace(/[’‘]/g,"'").replace(/[^a-z0-9']+/g,' ').trim().replace(/\s+/g,' ');
const T=[
{id:'present-simple',group:'Present',name:'Present Simple',uz:'Hozirgi oddiy zamon',form:'S + V1 / V-s(es)',neg:'S + do/does not + V1',q:'Do/Does + S + V1?',whenEn:'Use it for facts, routines, repeated actions and stable situations.',whenUz:'Faktlar, odatlar, takroriy ishlar va doimiy holatlar uchun ishlatiladi.',ielts:'Task 1 da umumiy faktlar; Task 2 da umumiy fikr va dalillar.',markers:['usually','often','every day','generally'],examples:[['Many students study online every day.','Ko‘plab talabalar har kuni onlayn o‘qiydi.'],['Technology plays a major role in modern education.','Texnologiya zamonaviy ta’limda katta rol o‘ynaydi.'],['The chart shows the percentage of commuters.','Diagramma qatnovchilarning foizini ko‘rsatadi.']],gap:['Governments ___ public services through taxation.','fund'],error:['Many people prefers online learning.','Many people prefer online learning.'],translation:['Ko‘p yoshlar har kuni ijtimoiy tarmoqlardan foydalanadi.','Many young people use social media every day.']},
{id:'present-continuous',group:'Present',name:'Present Continuous',uz:'Hozirgi davomiy zamon',form:'S + am/is/are + V-ing',neg:'S + am/is/are not + V-ing',q:'Am/Is/Are + S + V-ing?',whenEn:'Use it for actions happening now, temporary situations and developing trends.',whenUz:'Hozir bo‘layotgan ishlar, vaqtinchalik holatlar va rivojlanayotgan tendensiyalar uchun.',ielts:'Task 1 da hozir rivojlanayotgan trend; Speaking’da vaqtinchalik faoliyat.',markers:['now','currently','at the moment','increasingly'],examples:[['More people are working from home nowadays.','Hozir ko‘proq odam uydan ishlayapti.'],['The climate is becoming warmer.','Iqlim iliqlashib bormoqda.'],['I am preparing for the IELTS exam this month.','Men shu oy IELTS imtihoniga tayyorlanyapman.']],gap:['The number of electric cars ___ rapidly.','is increasing'],error:['People is spending more time online.','People are spending more time online.'],translation:['Shaharlar tez sur’atda kengayib bormoqda.','Cities are expanding rapidly.']},
{id:'present-perfect',group:'Present',name:'Present Perfect',uz:'Hozirgi tugallangan zamon',form:'S + have/has + V3',neg:'S + have/has not + V3',q:'Have/Has + S + V3?',whenEn:'Use it for past actions connected to the present, life experience, or unfinished time periods.',whenUz:'O‘tmishda boshlangan yoki sodir bo‘lgan, lekin hozir bilan bog‘liq natijalar va tajribalar uchun.',ielts:'Task 2 da recent change; Task 1 da hozirgacha bo‘lgan o‘zgarish.',markers:['since','for','already','recently'],examples:[['Online education has become increasingly popular.','Onlayn ta’lim tobora ommalashdi.'],['Governments have introduced new environmental laws.','Hukumatlar yangi ekologik qonunlarni joriy etdi.'],['The population has doubled since 1990.','Aholi 1990-yildan beri ikki baravar oshdi.']],gap:['The use of smartphones ___ dramatically since 2010.','has increased'],error:['The city have changed significantly.','The city has changed significantly.'],translation:['So‘nggi yillarda masofaviy ish keng tarqaldi.','Remote work has become widespread in recent years.']},
{id:'present-perfect-continuous',group:'Present',name:'Present Perfect Continuous',uz:'Hozirgi tugallangan davomiy zamon',form:'S + have/has been + V-ing',neg:'S + have/has not been + V-ing',q:'Have/Has + S + been + V-ing?',whenEn:'Use it for an activity that began in the past and has continued up to now, often emphasizing duration.',whenUz:'O‘tmishda boshlangan va hozirgacha davom etayotgan ishning davomiyligini ta’kidlash uchun.',ielts:'Speaking’da davom etayotgan o‘qish/ish; Task 2 da davomli trendni izohlash.',markers:['for','since','all day','recently'],examples:[['Researchers have been studying this issue for decades.','Tadqiqotchilar bu masalani o‘nlab yillardan beri o‘rganib kelmoqda.'],['I have been learning English since primary school.','Men boshlang‘ich maktabdan beri ingliz tilini o‘rganib kelaman.'],['Cities have been investing in public transport.','Shaharlar jamoat transportiga sarmoya kiritib kelmoqda.']],gap:['Scientists ___ climate change for many years.','have been studying'],error:['She has been work here since 2024.','She has been working here since 2024.'],translation:['Ular besh yildan beri bu muammoni o‘rganib kelmoqda.','They have been studying this problem for five years.']},
{id:'past-simple',group:'Past',name:'Past Simple',uz:'O‘tgan oddiy zamon',form:'S + V2',neg:'S + did not + V1',q:'Did + S + V1?',whenEn:'Use it for finished actions and states at a definite time in the past.',whenUz:'O‘tmishda aniq vaqtda tugagan ish yoki holatlar uchun.',ielts:'Task 1 dagi o‘tgan yillar ma’lumotlari; Speaking’dagi o‘tgan voqealar.',markers:['yesterday','in 2010','last year','ago'],examples:[['Sales rose sharply in 2015.','Savdo 2015-yilda keskin oshdi.'],['The government introduced the policy last year.','Hukumat siyosatni o‘tgan yili joriy etdi.'],['I started learning English when I was ten.','Men o‘n yoshimda ingliz tilini o‘rganishni boshladim.']],gap:['The figure ___ to 45% in 2018.','rose'],error:['The population increase rapidly in 2005.','The population increased rapidly in 2005.'],translation:['Kompaniya 2020-yilda yangi zavod ochdi.','The company opened a new factory in 2020.']},
{id:'past-continuous',group:'Past',name:'Past Continuous',uz:'O‘tgan davomiy zamon',form:'S + was/were + V-ing',neg:'S + was/were not + V-ing',q:'Was/Were + S + V-ing?',whenEn:'Use it for an action in progress at a particular time in the past or a longer action interrupted by another.',whenUz:'O‘tmishdagi ma’lum paytda davom etayotgan ish yoki boshqa voqea bilan bo‘lingan uzoqroq harakat uchun.',ielts:'Speaking hikoyalarida fon voqeasi; Task 2 misolida davom etayotgan o‘tmish holati.',markers:['while','when','at that time','at 8 pm'],examples:[['I was studying when the power went out.','Elektr o‘chganda men o‘qiyotgan edim.'],['People were moving to cities throughout the 1990s.','1990-yillar davomida odamlar shaharlarga ko‘chayotgan edi.'],['The company was expanding rapidly at that time.','O‘sha paytda kompaniya tez kengayayotgan edi.']],gap:['While prices ___, wages remained stable.','were rising'],error:['They was working when the survey began.','They were working when the survey began.'],translation:['Men universitetda o‘qiyotganimda yarim stavkada ishlayotgan edim.','I was working part-time while I was studying at university.']},
{id:'past-perfect',group:'Past',name:'Past Perfect',uz:'O‘tgan tugallangan zamon',form:'S + had + V3',neg:'S + had not + V3',q:'Had + S + V3?',whenEn:'Use it for an action completed before another point or action in the past.',whenUz:'O‘tmishdagi boshqa voqeadan oldin tugagan ishni ko‘rsatish uchun.',ielts:'Task 1 da oldingi nuqtani taqqoslash; Speaking hikoyasida voqealar ketma-ketligi.',markers:['before','after','by the time','already'],examples:[['By 2010, the figure had fallen to 20%.','2010-yilga kelib ko‘rsatkich 20% gacha tushgan edi.'],['The company had expanded before demand declined.','Talab pasayishidan oldin kompaniya kengaygan edi.'],['I had never travelled abroad before that trip.','O‘sha safargacha men hech qachon chet elga chiqmagan edim.']],gap:['By the time the policy changed, unemployment ___ significantly.','had fallen'],error:['After prices had rose, demand decreased.','After prices had risen, demand decreased.'],translation:['2015-yilga kelib aholi ikki baravar ko‘paygan edi.','By 2015, the population had doubled.']},
{id:'past-perfect-continuous',group:'Past',name:'Past Perfect Continuous',uz:'O‘tgan tugallangan davomiy zamon',form:'S + had been + V-ing',neg:'S + had not been + V-ing',q:'Had + S + been + V-ing?',whenEn:'Use it to emphasize the duration of an activity continuing up to a past point.',whenUz:'O‘tmishdagi bir nuqtagacha davom etgan ishning qancha vaqt davom etganini ta’kidlash uchun.',ielts:'Speaking hikoyalarida sabab/davomiylik; murakkab Task 2 misollarida.',markers:['for','since','before','when'],examples:[['They had been living there for ten years before they moved.','Ko‘chishdan oldin ular u yerda o‘n yil yashab kelgan edi.'],['Researchers had been collecting data before the project ended.','Loyiha tugashidan oldin tadqiqotchilar ma’lumot to‘plab kelayotgan edi.'],['I had been preparing for months when the exam was cancelled.','Imtihon bekor qilinganda men oylar davomida tayyorlanib kelayotgan edim.']],gap:['The team ___ data for months before publishing the report.','had been collecting'],error:['They had been study for two hours.','They had been studying for two hours.'],translation:['U ketishidan oldin uch yil shu yerda ishlab kelgan edi.','He had been working here for three years before he left.']},
{id:'future-simple',group:'Future',name:'Future Simple',uz:'Kelasi oddiy zamon',form:'S + will + V1',neg:'S + will not + V1',q:'Will + S + V1?',whenEn:'Use it for predictions, spontaneous decisions, promises and future facts.',whenUz:'Bashorat, shu zahoti qabul qilingan qaror, va’da va kelajak faktlari uchun.',ielts:'Task 2 da oqibat/bashorat; Task 1 future chartlarda kelajak ko‘rsatkichlari.',markers:['will','probably','in the future','next year'],examples:[['This trend will continue in the future.','Bu tendensiya kelajakda davom etadi.'],['The population will reach ten million by 2030.','Aholi 2030-yilgacha o‘n millionga yetadi.'],['Technology will change the way people work.','Texnologiya odamlarning ishlash usulini o‘zgartiradi.']],gap:['The demand for renewable energy ___ in the coming years.','will grow'],error:['People will uses more electric cars.','People will use more electric cars.'],translation:['Kelajakda ko‘proq odam masofadan ishlaydi.','More people will work remotely in the future.']},
{id:'future-continuous',group:'Future',name:'Future Continuous',uz:'Kelasi davomiy zamon',form:'S + will be + V-ing',neg:'S + will not be + V-ing',q:'Will + S + be + V-ing?',whenEn:'Use it for an action that will be in progress at a particular future time.',whenUz:'Kelajakdagi aniq paytda davom etayotgan bo‘ladigan ish uchun.',ielts:'Speaking’da rejalashtirilgan faoliyat; future process/trendni tavsiflashda kamroq ishlatiladi.',markers:['this time tomorrow','at 8 pm','next week'],examples:[['This time next year, I will be studying at university.','Kelasi yil shu paytda men universitetda o‘qiyotgan bo‘laman.'],['More people will be using electric vehicles by then.','O‘sha paytga kelib ko‘proq odam elektr transportidan foydalanayotgan bo‘ladi.'],['The company will be expanding into new markets.','Kompaniya yangi bozorlarga kengayib borayotgan bo‘ladi.']],gap:['At this time tomorrow, we ___ the final exam.','will be taking'],error:['She will be study abroad next year.','She will be studying abroad next year.'],translation:['Kelasi oy shu paytda men yangi kursda o‘qiyotgan bo‘laman.','This time next month, I will be studying on a new course.']},
{id:'future-perfect',group:'Future',name:'Future Perfect',uz:'Kelasi tugallangan zamon',form:'S + will have + V3',neg:'S + will not have + V3',q:'Will + S + have + V3?',whenEn:'Use it for an action that will be completed before a stated future time.',whenUz:'Kelajakdagi ma’lum vaqtgacha tugagan bo‘ladigan ish uchun.',ielts:'Task 1 forecastlarda “by 2030”; Speaking’da maqsad va rejalarning yakuni.',markers:['by','by the time','before','by 2030'],examples:[['By 2030, the city will have reduced emissions substantially.','2030-yilga kelib shahar chiqindilarni sezilarli kamaytirgan bo‘ladi.'],['I will have completed the course by June.','Iyun oyigacha kursni tugatgan bo‘laman.'],['The population will have reached eight million by then.','O‘sha paytga kelib aholi sakkiz millionga yetgan bo‘ladi.']],gap:['By 2040, many countries ___ coal use significantly.','will have reduced'],error:['By next year, I will have finish the programme.','By next year, I will have finished the programme.'],translation:['2030-yilgacha kompaniya yangi tizimni joriy qilgan bo‘ladi.','By 2030, the company will have introduced the new system.']},
{id:'future-perfect-continuous',group:'Future',name:'Future Perfect Continuous',uz:'Kelasi tugallangan davomiy zamon',form:'S + will have been + V-ing',neg:'S + will not have been + V-ing',q:'Will + S + have been + V-ing?',whenEn:'Use it to emphasize how long an activity will have continued by a future point.',whenUz:'Kelajakdagi bir nuqtaga kelib ish qancha vaqt davom etib kelgan bo‘lishini ta’kidlash uchun.',ielts:'Kam ishlatiladi; Speaking’da uzoq davom etgan kelajak faoliyati uchun tabiiy bo‘lsa ishlating.',markers:['for','by the time','by next year'],examples:[['By next year, I will have been studying English for five years.','Kelasi yilga kelib men ingliz tilini besh yil o‘rganib kelayotgan bo‘laman.'],['By 2030, the company will have been operating for fifty years.','2030-yilga kelib kompaniya ellik yildan beri faoliyat yuritayotgan bo‘ladi.'],['She will have been working there for a decade by then.','O‘sha paytga kelib u yerda o‘n yildan beri ishlayotgan bo‘ladi.']],gap:['By June, I ___ here for two years.','will have been working'],error:['By 2030, they will have been operate for 20 years.','By 2030, they will have been operating for 20 years.'],translation:['Kelasi oyga kelib u bu loyihada bir yil ishlayotgan bo‘ladi.','By next month, she will have been working on this project for a year.']}
];
let progress={};try{progress=JSON.parse(localStorage.getItem(STORAGE))||{}}catch{}
let selected=T[0].id, mode='lesson', qi=0, draft='', feedback=null;
function save(){try{localStorage.setItem(STORAGE,JSON.stringify(progress))}catch{};window.VocabCloud?.queue?.()}
function get(){return progress}
function set(v){progress=v&&typeof v==='object'?v:{};try{localStorage.setItem(STORAGE,JSON.stringify(progress))}catch{}}
function tense(){return T.find(x=>x.id===selected)||T[0]}
function optsFor(t){const others=T.filter(x=>x.id!==t.id).slice(0,3).map(x=>x.form);return [t.form,...others].sort(()=>Math.random()-.5)}
function exercises(t){
 const otherExamples=T.filter(x=>x.id!==t.id).slice(0,3).map(x=>x.examples[0][0]);
 return [
  {type:'mcq',label:'FORMULA',q:`${t.name} formulasi qaysi?`,options:optsFor(t),answer:t.form},
  {type:'mcq',label:'WHEN TO USE',q:'Qaysi izoh shu zamonga mos?',options:[t.whenEn,...T.filter(x=>x.id!==t.id).slice(0,3).map(x=>x.whenEn)].sort(()=>Math.random()-.5),answer:t.whenEn},
  {type:'mcq',label:'IDENTIFY',q:`Qaysi gap ${t.name}da yozilgan?`,options:[t.examples[0][0],...otherExamples].sort(()=>Math.random()-.5),answer:t.examples[0][0]},
  {type:'text',label:'GAP FILL',q:t.gap[0],answer:t.gap[1],model:t.gap[0].replace('___',t.gap[1])},
  {type:'text',label:'ERROR FIX',q:`Xatoni tuzating:\n${t.error[0]}`,answer:t.error[1],model:t.error[1]},
  {type:'text',label:'UZ → EN',q:`Inglizchaga tarjima qiling:\n${t.translation[0]}`,answer:t.translation[1],model:t.translation[1]},
  {type:'mcq',label:'TIME MARKER',q:`Qaysi marker ${t.name} bilan ko‘p ishlatiladi?`,options:[t.markers[0],'last century','right now','by yesterday'].filter((v,i,a)=>a.indexOf(v)===i).slice(0,4).sort(()=>Math.random()-.5),answer:t.markers[0]},
  {type:'text',label:'OWN SENTENCE',q:`${t.name}dan foydalanib Education yoki Technology mavzusida kamida 7 so‘zli bitta gap yozing.`,answer:'__own__',model:t.examples[1][0]}
 ];
}
function textCorrect(value,answer){const a=norm(value),b=norm(answer);if(answer==='__own__'){const words=a.split(' ').filter(Boolean);return words.length>=7}if(a===b)return true;const key=b.split(' ').filter(w=>w.length>3);return key.length&&key.filter(w=>a.includes(w)).length/Math.max(1,key.length)>=.72}
function render(root){const t=tense(),done=Object.values(progress).filter(x=>x?.completed).length;root.innerHTML=`<section class="tense-hero"><div><span>GRAMMAR CORE · B2–C1</span><h1>12 Tenses</h1><p>12 ta ingliz zamoni — formula, qachon ishlatilishi, IELTS’da qo‘llanishi, o‘zbekcha izoh va amaliy tekshiruv.</p></div><div class="tense-score"><strong>${done}/12</strong><small>mustahkamlangan</small></div></section><div class="tense-layout"><aside class="tense-list">${['Present','Past','Future'].map(g=>`<div class="tense-group"><b>${g}</b>${T.filter(x=>x.group===g).map(x=>`<button class="${x.id===selected?'active':''} ${progress[x.id]?.completed?'done':''}" data-tense-id="${x.id}"><span>${esc(x.name)}</span><small>${esc(x.uz)}</small></button>`).join('')}</div>`).join('')}</aside><section class="tense-detail">${mode==='lesson'?lesson(t):practice(t)}</section></div>`;bind(root)}
function lesson(t){return `<div class="tense-title"><div><span>${esc(t.group)} tense</span><h2>${esc(t.name)}</h2><p>${esc(t.uz)}</p></div><button class="tense-practice-btn" data-tense-action="practice">Mashqlarni boshlash →</button></div><div class="tense-form-grid"><article><small>POSITIVE</small><strong>${esc(t.form)}</strong></article><article><small>NEGATIVE</small><strong>${esc(t.neg)}</strong></article><article><small>QUESTION</small><strong>${esc(t.q)}</strong></article></div><article class="tense-explain"><h3>When do we use it?</h3><p>${esc(t.whenEn)}</p><h3>Qachon ishlatiladi?</h3><p>${esc(t.whenUz)}</p><div class="tense-ielts"><b>IELTS use</b><span>${esc(t.ielts)}</span></div><div class="tense-markers"><b>Common markers</b>${t.markers.map(m=>`<span>${esc(m)}</span>`).join('')}</div></article><div class="tense-examples"><h3>3 ta IELTS uslubidagi misol</h3>${t.examples.map((e,i)=>`<article><b>${i+1}. ${esc(e[0])}</b><span>${esc(e[1])}</span></article>`).join('')}</div>`}
function practice(t){const qs=exercises(t),q=qs[qi],saved=progress[t.id]||{},answered=saved.answers?.[qi]??draft;return `<div class="tense-practice-head"><button data-tense-action="lesson">← Darsga qaytish</button><div><small>${esc(q.label)} · ${qi+1}/${qs.length}</small><h2>${esc(t.name)}</h2></div><span>${saved.best||0}/${qs.length}</span></div><article class="tense-question"><p>${esc(q.q).replace(/\n/g,'<br>')}</p>${q.type==='mcq'?`<div class="tense-options">${q.options.map(o=>`<label><input type="radio" name="tenseAnswer" value="${esc(o)}" ${answered===o?'checked':''}><span>${esc(o)}</span></label>`).join('')}</div>`:`<textarea id="tenseTextAnswer" placeholder="Javobingizni yozing...">${esc(answered||'')}</textarea>`}${feedback?`<div class="tense-feedback ${feedback.ok?'ok':'bad'}"><strong>${feedback.ok?'✓ To‘g‘ri':'✕ Qayta ko‘ring'}</strong><p>${feedback.ok?'Javob qabul qilindi.':`Model: ${esc(q.model||q.answer)}`}</p></div>`:''}<div class="tense-actions"><button data-tense-action="prev" ${qi===0?'disabled':''}>← Oldingi</button><button class="check" data-tense-action="check">Tekshirish</button><button data-tense-action="next" ${qi===qs.length-1?'disabled':''}>Keyingi →</button></div></article>`}
function bind(root){root.querySelectorAll('[data-tense-id]').forEach(b=>b.onclick=()=>{selected=b.dataset.tenseId;mode='lesson';qi=0;draft='';feedback=null;render(root)});root.querySelectorAll('[data-tense-action]').forEach(b=>b.onclick=()=>act(root,b.dataset.tenseAction));root.querySelectorAll('input[name=tenseAnswer]').forEach(i=>i.onchange=()=>{draft=i.value;feedback=null});const ta=root.querySelector('#tenseTextAnswer');if(ta)ta.oninput=()=>{draft=ta.value;feedback=null}}
function act(root,a){const t=tense(),qs=exercises(t),q=qs[qi];if(a==='lesson'){mode='lesson';feedback=null;draft='';render(root);return}if(a==='practice'){mode='practice';qi=0;feedback=null;draft='';render(root);return}if(a==='prev'){qi=Math.max(0,qi-1);feedback=null;draft=progress[t.id]?.answers?.[qi]||'';render(root);return}if(a==='next'){qi=Math.min(qs.length-1,qi+1);feedback=null;draft=progress[t.id]?.answers?.[qi]||'';render(root);return}if(a==='check'){let value=draft;if(q.type==='mcq')value=root.querySelector('input[name=tenseAnswer]:checked')?.value||'';else value=root.querySelector('#tenseTextAnswer')?.value||'';const ok=q.type==='mcq'?value===q.answer:textCorrect(value,q.answer);const st=progress[t.id]||{answers:{},correct:{},best:0,completed:false};st.answers=st.answers||{};st.correct=st.correct||{};st.answers[qi]=value;st.correct[qi]=ok;st.best=Object.values(st.correct).filter(Boolean).length;st.completed=st.best>=7;progress[t.id]=st;save();feedback={ok};draft=value;render(root)}}
window.TensesModule={render,getProgress:get,setProgress:set,count:T.length};
})();
