(()=>{
'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s||'').toLowerCase().replace(/[’‘]/g,"'").replace(/[^a-z0-9\s']/g,' ').replace(/\s+/g,' ').trim();
const words=s=>norm(s).split(' ').filter(Boolean);
const stop=new Set('the a an and or but to of in on at for from with by is are was were be been being this that these those it its as if then than i we you they he she my our your their some many more most very can could should would will may might do does did have has had about into over under between while although because therefore however'.split(' '));
const contentWords=s=>words(s).filter(x=>x.length>3&&!stop.has(x));
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
function seededShuffle(arr,seed){let x=0;for(const ch of String(seed))x=(x*31+ch.charCodeAt(0))>>>0;const a=[...arr];for(let i=a.length-1;i>0;i--){x=(1664525*x+1013904223)>>>0;const j=x%(i+1);[a[i],a[j]]=[a[j],a[i]]}return a}
let data=null,loading=null;
let ui={tab:'course',maxWriteTopic:0,maxWriteQuery:'',maxWriteWheel:null,day:1,exercise:'idea',samplePage:0,sampleQuery:'',sampleTask:'all',sampleSource:'all',sampleId:null,grammarTask:'book',grammarId:null,grammarN:0,grammarPractice:false,collocTopic:0,collocFlip:{},ideaIndex:0,mockTask:'task2',mockIndex:0,mockTimer:null,mockLeft:0,paintRole:'thesis'};
let progress={done:{},notes:{},sampleTags:{},grammar:{},grammarAnswers:{},expressionAnswers:{},collocationKnown:{},mockHistory:[]};
const roles={thesis:['🟣','Thesis / position'],main:['🔵','Main idea'],explanation:['🟢','Explanation'],example:['🟡','Example'],cohesion:['🟠','Cohesion'],grammar:['🔴','Advanced grammar']};
const roleOrder=['thesis','main','explanation','example','cohesion','grammar'];
function key(){return window.VocabCloud?.key('vocab-atlas-writing-booster-v2')||'vocab-atlas-writing-booster-v2'}
function loadProgress(){try{const raw=localStorage.getItem(key())||localStorage.getItem(window.VocabCloud?.key?.('vocab-atlas-writing-booster-v1')||'vocab-atlas-writing-booster-v1');const old=JSON.parse(raw||'{}')||{};progress={...progress,...old}}catch{};for(const k of ['done','notes','sampleTags','grammar','grammarAnswers','expressionAnswers','collocationKnown'])progress[k]||={};progress.mockHistory||=[];return progress}
function save(){try{localStorage.setItem(key(),JSON.stringify(progress))}catch{}window.VocabCloud?.queue?.()}
function getProgress(){return loadProgress()}
function setProgress(v){progress={done:{},notes:{},sampleTags:{},grammar:{},grammarAnswers:{},expressionAnswers:{},collocationKnown:{},mockHistory:[],...(v&&typeof v==='object'?v:{})};save()}
async function ensure(){if(data)return data;if(loading)return loading;loading=fetch('writing-data.json').then(r=>{if(!r.ok)throw Error('Writing data yuklanmadi');return r.json()}).then(d=>{data=d;loadProgress();return d}).finally(()=>loading=null);return loading}
function sampleById(id){return data.samples.find(x=>x.id===id)}
function sourceCounts(){return Object.entries(data.sampleCounts||{}).sort((a,b)=>b[1]-a[1])}
function sentenceParagraphs(answer){return String(answer||'').split(/\n\s*\n/).map(x=>x.trim()).filter(Boolean)}
function splitSentences(t){return String(t||'').replace(/\n/g,' ').split(/(?<=[.!?])\s+(?=[A-Z])/).map(x=>x.trim()).filter(Boolean)}
function sourceIdeas(sample){const out=[];if(sample?.outline){for(const line of sample.outline.split('\n'))if(/^(Support|Argument|Thesis)/i.test(line.trim()))out.push(line.trim())}if(!out.length){for(const r of sample?.roles||[])if(['main','thesis','example'].includes(r.role)&&!out.includes(r.text))out.push(r.text)}return out.slice(0,6)}
function doneKey(day,type,i){return `${day}:${type}:${i}`}
function isDone(day,type,i){return !!progress.done[doneKey(day,type,i)]}
function dayDone(day){const d=data.days[day-1];let total=0,done=0;for(const [t,n] of Object.entries(d.counts)){for(let i=0;i<n;i++){total++;if(isDone(day,t,i))done++}}return{done,total,pct:total?Math.round(done*100/total):0}}
function markDone(k,ok){progress.done[k]=!!ok;save()}
function heading(){const total=Object.values(progress.done).filter(Boolean).length;return `<div class="wb-hero"><div class="wb-hero-copy"><div class="wb-creator-badge"><span>✍️</span><strong>WRITING</strong><b>9.0</b></div><span class="wb-kicker">VIVID IELTS · WRITING LAB</span><h1>50 kunlik Writing Mastery</h1><p>Har bir mashqda real Tekshirish · full-essay color analysis · Uzbek grammar support.</p></div><div class="wb-hero-stat"><strong>${total}</strong><span>tekshirib bajarilgan</span></div></div>`}
function tabs(){const items=[['course','50 kun'],['ideas','Idea Bank'],['samples','Sample Answers'],['maxwrite','Writing Topic Collocations'],['expressions','15-card Collocations'],['grammar','Writing Grammar'],['mock','Writing Mock']];return `<div class="wb-tabs">${items.map(([id,t])=>`<button class="${ui.tab===id?'active':''}" data-writing-action="tab" data-tab="${id}">${t}</button>`).join('')}</div>`}
async function render(root){await ensure();root.innerHTML=heading()+tabs()+`<section id="wbBody" class="wb-body"></section>`;renderBody()}
function renderBody(){const el=document.getElementById('wbBody');if(!el)return;if(ui.tab==='course')renderCourse(el);else if(ui.tab==='ideas')renderIdeas(el);else if(ui.tab==='samples')renderSamples(el);else if(ui.tab==='maxwrite')renderMaxWrite(el);else if(ui.tab==='expressions')renderExpressions(el);else if(ui.tab==='grammar')renderGrammar(el);else renderMock(el)}
function renderCourse(el){const d=data.days[ui.day-1],stat=dayDone(ui.day);const names={idea:'1 · Idea Builder',outline:'2 · Outline Builder',detective:'3 · Band 9 Detective',reconstruct:'4 · Paragraph Reconstruction',missing:'5 · Missing Sentence',upgrade:'6 · Sentence Upgrade',expression:'7 · Vocabulary → Sentence → Paragraph',bad:'8 · Error Challenge',task1:'9 · Task 1 Lab'};el.innerHTML=`<div class="wb-course-head"><div><div class="wb-day-nav"><button data-writing-action="day-prev" ${ui.day===1?'disabled':''}>←</button><strong>DAY ${ui.day} / 50</strong><button data-writing-action="day-next" ${ui.day===50?'disabled':''}>→</button></div><h2>${esc(d.topic)}</h2><p>${Object.values(d.counts).reduce((a,b)=>a+b,0)} ta micro-task · har birida Tekshirish.</p></div><div class="wb-ring"><strong>${stat.pct}%</strong><span>${stat.done}/${stat.total}</span></div></div><div class="wb-progress"><i style="width:${stat.pct}%"></i></div><div class="wb-exercise-nav">${Object.entries(names).map(([id,n])=>`<button class="${ui.exercise===id?'active':''}" data-writing-action="exercise" data-exercise="${id}">${n}<b>${d.counts[id]}</b></button>`).join('')}</div><div id="wbExercise"></div>`;renderExercise(d)}
function renderExercise(day){const el=document.getElementById('wbExercise'),type=ui.exercise,n=day.counts[type],refs=day.refs[type]||[];el.innerHTML=`<div class="wb-ex-title"><h3>${n} ta mashq</h3><p>Avval o‘zingiz bajaring, keyin <b>Tekshirish</b>ni bosing. Model/javob tekshirgandan keyin chiqadi.</p></div><div class="wb-task-list">${Array.from({length:n},(_,i)=>exerciseCard(day,type,i,sampleById(refs[i%refs.length]))).join('')}</div>`}
function feedbackBox(dk){return `<div class="wb-feedback" data-feedback="${esc(dk)}"></div>`}
function checkBtn(day,type,i){return `<footer><button class="wb-check" data-writing-action="check-course" data-day="${day.day}" data-type="${type}" data-index="${i}">Tekshirish</button></footer>`}
function paragraphFor(s,i){const paras=sentenceParagraphs(s.answer);return paras[Math.min(1+(i%Math.max(1,paras.length-1)),Math.max(0,paras.length-1))]||paras[0]||s.answer}
function reconstructSpec(day,type,i,s){const p=paragraphFor(s,i);let ss=(s.roles||[]).filter(r=>p.includes(r.text)).map(r=>r.text);if(ss.length<3)ss=splitSentences(p);ss=ss.slice(0,6);const shuffled=seededShuffle(ss,`${day.day}-${type}-${i}-${s.id}`);const labels=shuffled.map((_,j)=>String.fromCharCode(65+j));const correct=ss.map(x=>labels[shuffled.indexOf(x)]).join(' ');return{p,ss,shuffled,labels,correct}}
function missingSpec(day,i,s){const ss=(s.roles||[]).map(x=>x.text).filter(Boolean).length?(s.roles||[]).map(x=>x.text):splitSentences(s.answer);const pos=(i*3+day.day)%Math.max(1,ss.length),target=ss[pos]||ss[0]||'',before=ss[Math.max(0,pos-1)]||'',after=ss[Math.min(ss.length-1,pos+1)]||'';const distract=seededShuffle(data.samples.filter(x=>x.id!==s.id).flatMap(x=>(x.roles||[]).slice(0,1).map(r=>r.text)).filter(Boolean),`${day.day}-${i}-missing`).slice(0,3);return{target,before,after,opts:seededShuffle([target,...distract],`${day.day}-${i}-opts`)}}
function paintPalette(context){return `<div class="wb-paint-tools"><span>Gapni sichqoncha bilan belgilang → ranglar chiqadi → kerakli rangni tanlang. Xohlasangiz rangni oldindan tanlab gapni bosishingiz ham mumkin.</span>${roleOrder.map(r=>`<button class="wb-paint ${ui.paintRole===r?'active':''} role-${r}" data-writing-action="paint-role" data-role="${r}" data-context="${esc(context)}">${roles[r][0]} ${roles[r][1]}</button>`).join('')}<button class="wb-paint erase" data-writing-action="paint-role" data-role="erase" data-context="${esc(context)}">⌫ Tozalash</button></div>`}
function paintEssayHTML(s,context){const saved=progress.sampleTags[s.id]||{};const rs=(s.roles&&s.roles.length)?s.roles:splitSentences(s.answer).map((text,i)=>({text,role:'explanation',p:0}));const groups={};rs.forEach((r,i)=>{(groups[r.p??0]??=[]).push({...r,i})});return `${paintPalette(context)}<div class="wb-highlight-essay" data-sample="${esc(s.id)}" data-context="${esc(context)}">${Object.keys(groups).sort((a,b)=>a-b).map(p=>`<p>${groups[p].map(r=>`<span class="wb-paint-sentence ${saved[r.i]?`role-${saved[r.i]}`:''}" data-role-index="${r.i}" data-sample="${esc(s.id)}" data-picked="${esc(saved[r.i]||'')}">${esc(r.text)}</span>`).join(' ')}</p>`).join('')}</div><div class="wb-paint-feedback"></div>`}
function exerciseCard(day,type,i,s){if(!s)return'';const dk=doneKey(day.day,type,i),done=isDone(day.day,type,i),ideas=sourceIdeas(s);let body='';
 if(type==='idea')body=`<p class="wb-prompt">${esc(s.prompt)}</p><label>2 ta kuchli idea yozing: har biri <b>idea → why → result/example</b>.</label><textarea data-writing-note="${dk}" placeholder="Idea 1...\n\nIdea 2...">${esc(progress.notes[dk]||'')}</textarea>`;
 else if(type==='outline')body=`<p class="wb-prompt">${esc(s.prompt)}</p><label>Position + BP1 + BP2 + example yozing.</label><textarea data-writing-note="${dk}" placeholder="Position: ...\nBP1: ...\nBP2: ...\nExample: ...">${esc(progress.notes[dk]||'')}</textarea>`;
 else if(type==='detective')body=`<p class="wb-prompt">${esc(s.prompt)}</p><p><b>FULL ESSAY.</b> Rangni tanlang, keyin sichqoncha bilan gap(lar)ni belgilang. Oxirida Tekshirish.</p>${paintEssayHTML(s,`course-${dk}`)}`;
 else if(type==='reconstruct'){const sp=reconstructSpec(day,type,i,s);body=`<p>Gaplarni original paragraph tartibiga keltiring. Javobni harflar bilan yozing (masalan: B A C D).</p><div class="wb-reorder-list">${sp.shuffled.map((x,k)=>`<div><b>${sp.labels[k]}</b><span>${esc(x)}</span></div>`).join('')}</div><input class="wb-short-answer" data-writing-note="${dk}" placeholder="Masalan: C A B D" value="${esc(progress.notes[dk]||'')}">`}
 else if(type==='missing'){const sp=missingSpec(day,i,s);body=`<p>${esc(sp.before)}</p><div class="wb-blank">[ MISSING SENTENCE ]</div><p>${esc(sp.after)}</p><div class="wb-options">${sp.opts.map((x,k)=>`<label><input type="radio" name="miss-${day.day}-${i}" data-missing-choice value="${esc(x)}"> <b>${String.fromCharCode(65+k)}.</b> ${esc(x)}</label>`).join('')}</div>`}
 else if(type==='upgrade'){const e=data.expressions[(day.day*31+i)%data.expressions.length];body=`<p>Oddiy gapni tabiiy Band 7–8+ uslubida kuchaytiring.</p><div class="wb-basic">People have different views about ${esc(day.topic.toLowerCase())}.</div><textarea data-writing-note="${dk}" placeholder="Kuchliroq sentence...">${esc(progress.notes[dk]||'')}</textarea><div class="wb-hidden-model" data-model-expression="${esc(e?.text||ideas[0]||'')}"></div>`}
 else if(type==='expression'){const e=data.expressions[(day.day*17+i)%data.expressions.length];body=`<div class="wb-expression">${esc(e?.text||'')}</div><p>1) Expressionni tabiiy gapda ishlating. 2) Uni 2–3 gaplik mini-paragraphga rivojlantiring.</p><textarea data-writing-note="${dk}">${esc(progress.notes[dk]||'')}</textarea><small>Source: ${esc(e?.topic||'Writing source')}</small>`}
 else if(type==='bad'){const model=paragraphFor(s,i),weak=weakParagraph(model,day.topic);body=`<div class="wb-bad"><strong>❌ Weak paragraph</strong><p>${esc(weak)}</p></div><label>Muammolarni tuzating va paragraphni kuchli qayta yozing.</label><textarea data-writing-note="${dk}">${esc(progress.notes[dk]||'')}</textarea><div class="wb-hidden-model" data-band8="${esc(model)}"></div>`}
 else {const paras=sentenceParagraphs(s.answer);body=`<span class="wb-badge">TASK 1</span><h4>${esc(s.title)}</h4><p class="wb-prompt">${esc(s.prompt)}</p><label>Overview / key features yozing.</label><textarea data-writing-note="${dk}">${esc(progress.notes[dk]||'')}</textarea><div class="wb-hidden-model" data-task1model="${esc(paras.slice(0,2).join('\n\n'))}"></div>`}
 return `<article class="wb-task ${done?'done':''}" data-card-key="${esc(dk)}"><header><span>${i+1} / ${day.counts[type]}</span><b>${esc(s.source)}</b></header>${body}${feedbackBox(dk)}${checkBtn(day,type,i)}</article>`}
function weakParagraph(model,topic){const ss=splitSentences(model),core=ss[0]||'This topic is important.';return `${topic} is important. ${core.split(',')[0]}. This is good for people. There are many reasons for this. For example, it can help people. Therefore, it is very important.`}
function overlap(user,model){const m=[...new Set(contentWords(model))];if(!m.length)return 0;const u=new Set(contentWords(user));return m.filter(x=>u.has(x)).length/m.length}
function modelPanel(title,html){return `<div class="wb-model-panel"><b>${esc(title)}</b>${html}</div>`}
function setCourseFeedback(card,ok,score,msg,model=''){const fb=card.querySelector('.wb-feedback');fb.className=`wb-feedback ${ok?'ok':'no'}`;fb.innerHTML=`<strong>${ok?'✓':'↻'} ${esc(score)}</strong><p>${esc(msg)}</p>${model}`;card.classList.toggle('done',ok)}
function checkCourse(dayN,type,i){const day=data.days[dayN-1],refs=day.refs[type]||[],s=sampleById(refs[i%refs.length]);if(!s)return;const dk=doneKey(dayN,type,i),card=document.querySelector(`[data-card-key="${CSS.escape(dk)}"]`);if(!card)return;const user=String(progress.notes[dk]||'').trim();let ok=false,score='',msg='',model='';
 if(type==='idea'){const ideas=sourceIdeas(s).slice(0,4),parts=user.split(/\n\s*\n|\n(?=(?:idea\s*\d|\d+[.)]))/i).filter(x=>words(x).length>=6);const wc=words(user).length;ok=parts.length>=2||wc>=28;score=ok?'2/2 idea format':'Idea yetarli emas';msg=ok?'Ikki rivojlantirilgan fikr bor. Model bilan solishtiring.':'Kamida 2 alohida idea va har biriga sabab/natija yoki misol yozing.';model=modelPanel('Model ideas',`<ul>${ideas.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`)}
 else if(type==='outline'){const wc=words(user).length,lines=user.split(/\n+/).filter(x=>x.trim()).length;ok=wc>=28&&(lines>=4||/[.!?].*[.!?].*[.!?]/s.test(user));score=ok?'4/4 elementga yaqin':'Outline to‘liq emas';msg=ok?'Position, body ideas va support yetarli hajmda.':'Position + BP1 + BP2 + example ni aniq ajrating.';model=modelPanel('Source outline / model structure',`<pre>${esc(s.outline||sourceIdeas(s).join('\n'))}</pre>`)}
 else if(type==='detective'){const res=checkPaintedEssay(card,s);ok=res.pct>=65;score=`${res.correct}/${res.total} · ${res.pct}%`;msg=ok?'Dominant funksiyalar yaxshi ajratildi.':'Ranglarni qayta ko‘rib chiqing; qizil chegarali gaplarda dominant funksiya mos emas.';model=res.html}
 else if(type==='reconstruct'){const sp=reconstructSpec(day,type,i,s),ans=user.toUpperCase().replace(/[^A-Z]/g,' ' ).replace(/\s+/g,' ').trim();ok=ans===sp.correct;score=ok?'To‘g‘ri tartib':'Tartib xato';msg=ok?'Paragraph progression to‘g‘ri tiklandi.':'Topic sentence → explanation → example/result progressionini qayta tekshiring.';model=modelPanel('To‘g‘ri paragraph',`<p>${esc(sp.p)}</p><small>Javob: ${esc(sp.correct)}</small>`)}
 else if(type==='missing'){const chosen=card.querySelector('[data-missing-choice]:checked')?.value||'',sp=missingSpec(day,i,s);ok=norm(chosen)===norm(sp.target);score=ok?'To‘g‘ri':'Noto‘g‘ri';msg=ok?'Gap context va progressionga mos.':'Oldingi va keyingi gap bilan mantiqiy bog‘lanishni tekshiring.';model=ok?modelPanel('Original sentence',`<p>${esc(sp.target)}</p>`):''}
 else if(type==='upgrade'){const hint=card.querySelector('[data-model-expression]')?.dataset.modelExpression||'',wc=words(user).length,complex=/\b(although|while|whereas|which|because|despite|however|therefore|not only|rather than|in my view)\b/i.test(user);ok=wc>=10&&complex;score=ok?'Band 7–8+ structure mavjud':'Yana kuchaytiring';msg=ok?'Gapda murakkabroq grammar/linking va yetarli development bor.':'Kamida 10 so‘z va bitta tabiiy complex/linking structure ishlating.';model=modelPanel('Useful model expression',`<p>${esc(hint)}</p>`)}
 else if(type==='expression'){const e=data.expressions[(day.day*17+i)%data.expressions.length],target=e?.text||'',keys=contentWords(target).slice(0,3),low=norm(user);const used=keys.filter(k=>low.includes(k)).length;ok=words(user).length>=22&&used>=Math.min(2,keys.length);score=ok?'Expression ishlatildi':'Expression yetarli ishlatilmagan';msg=ok?'Expression tabiiy kontekstda va mini-paragraph hajmida ishlatilgan.':'Expressionning asosiy so‘zlarini saqlab, kamida 2–3 gap yozing.';model=modelPanel('Original useful expression',`<p>${esc(target)}</p>`)}
 else if(type==='bad'){const modelText=card.querySelector('[data-band8]')?.dataset.band8||'',wc=words(user).length,links=(user.match(/\b(for example|therefore|because|while|although|as a result|this means|in addition|however)\b/gi)||[]).length;ok=wc>=45&&links>=1;score=ok?'Kuchli rewrite':'Rewrite hali qisqa/zaif';msg=ok?'Paragraphda development va linking bor. Endi Band 8+ model bilan solishtiring.':'Kamida 45 so‘z, clear main idea, explanation va support yozing.';model=modelPanel('Mukammal Band 8+ model',`<p>${esc(modelText)}</p>`)}
 else {const modelText=card.querySelector('[data-task1model]')?.dataset.task1model||'',wc=words(user).length,overview=/\b(overall|it is clear|it is noticeable|the most noticeable|in general)\b/i.test(user);ok=wc>=25&&overview;score=ok?'Overview structure bor':'Overview yetarli emas';msg=ok?'Umumiy trend/key feature aniq signal qilingan.':'Kamida 25 so‘z va Overall / It is clear that kabi overview signalidan foydalaning.';model=modelPanel('Band 9 sample opening + overview',`<p>${esc(modelText)}</p>`)}
 markDone(dk,ok);setCourseFeedback(card,ok,score,msg,model);updateCourseStats()}
function updateCourseStats(){const stat=dayDone(ui.day),ring=document.querySelector('.wb-ring'),bar=document.querySelector('.wb-progress i');if(ring)ring.innerHTML=`<strong>${stat.pct}%</strong><span>${stat.done}/${stat.total}</span>`;if(bar)bar.style.width=stat.pct+'%';const nav=document.getElementById('navWriting');if(nav)nav.textContent=Object.values(progress.done).filter(Boolean).length}
function renderIdeas(el){const liz=data.lizIdeas||[],selected=liz[ui.ideaIndex%Math.max(1,liz.length)]||{title:'IELTS Ideas',notes:[],vocab:[]},keys=norm(selected.title).split(' ').filter(x=>x.length>3),pool=data.samples.filter(s=>s.task!=='task1'&&keys.some(k=>norm(s.title+' '+s.prompt).includes(k))).slice(0,8),notes=selected.notes||[],vocab=selected.vocab||[];el.innerHTML=`<div class="wb-section-head"><div><span class="wb-kicker">IELTS LIZ · IDEA BANK</span><h2>Ready Ideas + Vocabulary</h2><p>Topic bo‘yicha idea, vocabulary va model development.</p></div><select id="wbLizTopic">${liz.map((x,i)=>`<option value="${i}" ${i===ui.ideaIndex%Math.max(1,liz.length)?'selected':''}>${i+1}. ${esc(x.title)}</option>`).join('')}</select></div><article class="wb-liz-card"><span class="wb-badge">IELTS LIZ</span><h2>${esc(selected.title)}</h2>${notes.length?`<h3>Ready ideas / argument notes</h3><ul>${notes.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:'<p>Bu topicda extracted ready-idea jumlalari kam; vocabulary va related model developmentdan foydalaning.</p>'}${vocab.length?`<h3>Vocabulary</h3><div class="wb-vocab-chips">${vocab.map(x=>`<span>${esc(x)}</span>`).join('')}</div>`:''}</article><h3 class="wb-related-title">Related model ideas</h3><div class="wb-idea-grid">${(pool.length?pool:data.samples.filter(s=>s.task==='task2').slice(ui.ideaIndex,ui.ideaIndex+8)).map(s=>`<article><span>${esc(s.source)}</span><h3>${esc(s.title)}</h3><p>${esc(s.prompt)}</p><ul>${sourceIdeas(s).slice(0,4).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></article>`).join('')}</div>`}
function filteredSamples(){return data.samples.filter(s=>(ui.sampleTask==='all'||s.task===ui.sampleTask)&&(ui.sampleSource==='all'||s.source===ui.sampleSource)&&(!ui.sampleQuery||norm(s.title+' '+s.prompt).includes(norm(ui.sampleQuery))))}
function renderSamples(el){if(ui.sampleId){renderSampleDetail(el,sampleById(ui.sampleId));return}const list=filteredSamples(),per=12,pages=Math.max(1,Math.ceil(list.length/per));ui.samplePage=clamp(ui.samplePage,0,pages-1);const page=list.slice(ui.samplePage*per,(ui.samplePage+1)*per);el.innerHTML=`<div class="wb-section-head"><div><span class="wb-kicker">ALL SAMPLE ANSWERS</span><h2>Sample Answers Library · ${list.length}</h2><p>Full essay + mouse color analysis + Tekshirish.</p></div></div><div class="wb-filters"><input id="wbSampleQuery" placeholder="Topic qidirish…" value="${esc(ui.sampleQuery)}"><select id="wbSampleTask"><option value="all">Task 1 + Task 2 + Practice</option><option value="task2" ${ui.sampleTask==='task2'?'selected':''}>Task 2</option><option value="task1" ${ui.sampleTask==='task1'?'selected':''}>Task 1</option><option value="practice" ${ui.sampleTask==='practice'?'selected':''}>240 Topics models</option></select><select id="wbSampleSource"><option value="all">Barcha manbalar</option>${sourceCounts().map(([s,n])=>`<option value="${esc(s)}" ${ui.sampleSource===s?'selected':''}>${esc(s)} · ${n}</option>`).join('')}</select></div><div class="wb-sample-grid">${page.map(s=>`<button class="wb-sample-card" data-writing-action="open-sample" data-id="${esc(s.id)}"><span>${esc(s.source)} · ${esc(s.task.toUpperCase())}</span><h3>${esc(s.title)}</h3><p>${esc(s.prompt.slice(0,220))}${s.prompt.length>220?'…':''}</p><b>Full essay + Color Analysis →</b></button>`).join('')}</div><div class="wb-pager"><button data-writing-action="sample-prev" ${ui.samplePage===0?'disabled':''}>← Oldingi</button><span>${ui.samplePage+1} / ${pages}</span><button data-writing-action="sample-next" ${ui.samplePage===pages-1?'disabled':''}>Keyingi →</button></div>`}
function renderSampleDetail(el,s){if(!s){ui.sampleId=null;renderSamples(el);return}el.innerHTML=`<button class="wb-back" data-writing-action="sample-back">← Sample Answers</button><div class="wb-sample-detail"><div class="wb-sample-meta"><span>${esc(s.source)}</span><span>${esc(s.task.toUpperCase())}</span>${s.band?`<span>Band ${esc(s.band)}</span>`:''}</div><h2>${esc(s.title)}</h2><div class="wb-prompt">${esc(s.prompt)}</div><p class="wb-instruction"><b>FULL ESSAY:</b> rangni tanlang → sichqoncha bilan gapni yoki gaplar guruhini belgilang → oxirida Tekshirish.</p>${paintEssayHTML(s,`sample-${s.id}`)}<div class="wb-actions"><button class="wb-check" data-writing-action="paint-check" data-id="${esc(s.id)}">Tekshirish</button><button data-writing-action="paint-clear" data-id="${esc(s.id)}">Ranglarni tozalash</button></div>${s.outline?`<details><summary>Outline</summary><pre>${esc(s.outline)}</pre></details>`:''}</div>`}
function setPaintRoleClass(span,role){roleOrder.forEach(r=>span.classList.remove(`role-${r}`));span.classList.remove('paint-ok','paint-wrong');if(role&&role!=='erase')span.classList.add(`role-${role}`);span.dataset.picked=role==='erase'?'':role}
function applyRoleToSpan(span,role){const id=span.dataset.sample,idx=span.dataset.roleIndex;progress.sampleTags[id]||={};if(role==='erase')delete progress.sampleTags[id][idx];else progress.sampleTags[id][idx]=role;setPaintRoleClass(span,role);save()}
function applySelection(essay){const sel=window.getSelection();if(!sel||sel.isCollapsed||!essay.contains(sel.anchorNode)||!essay.contains(sel.focusNode))return;const range=sel.getRangeAt(0),spans=[...essay.querySelectorAll('.wb-paint-sentence')];let touched=[];for(const sp of spans){try{if(range.intersectsNode(sp))touched.push(sp)}catch{}}if(!touched.length)return;document.querySelectorAll('.wb-paint-sentence.pending-paint').forEach(x=>x.classList.remove('pending-paint'));touched.forEach(x=>x.classList.add('pending-paint'));window.__wbPendingPaint={essay,spans:touched};let box=essay.parentElement.querySelector('.wb-floating-palette');if(!box){box=document.createElement('div');box.className='wb-floating-palette';essay.insertAdjacentElement('afterend',box)}box.innerHTML=`<b>${touched.length} ta gap tanlandi. Rangni tanlang:</b>${roleOrder.map(r=>`<button class="wb-paint role-${r}" data-writing-action="paint-pending" data-role="${r}">${roles[r][0]} ${roles[r][1]}</button>`).join('')}<button class="wb-paint erase" data-writing-action="paint-pending" data-role="erase">⌫</button>`;box.classList.add('show');sel.removeAllRanges()}
function checkPaintedEssay(container,s){const saved=progress.sampleTags[s.id]||{},spans=[...container.querySelectorAll(`.wb-highlight-essay[data-sample="${CSS.escape(s.id)}"] .wb-paint-sentence`)];let correct=0,total=s.roles?.length||spans.length,answered=0;spans.forEach(sp=>{const i=Number(sp.dataset.roleIndex),got=saved[i]||'',exp=s.roles?.[i]?.role||'explanation';sp.classList.remove('paint-ok','paint-wrong');if(got){answered++;if(got===exp){correct++;sp.classList.add('paint-ok');sp.title='✓ To‘g‘ri'}else{sp.classList.add('paint-wrong');sp.title=`To‘g‘ri: ${roles[exp][0]} ${roles[exp][1]}`}}else{sp.classList.add('paint-wrong');sp.title=`Belgilanmagan · to‘g‘ri: ${roles[exp][0]} ${roles[exp][1]}`}});const pct=total?Math.round(correct*100/total):0,html=`<div class="wb-paint-summary"><b>${correct}/${total} · ${pct}%</b><span>Belgilangani: ${answered}/${total}. Qizil chegarali gap ustiga kursor olib borsangiz to‘g‘ri funksiyani ko‘rasiz.</span></div>`;const fb=container.querySelector('.wb-paint-feedback');if(fb)fb.innerHTML=html;return{correct,total,pct,html}}
function maxWriteData(){const bank=window.VividMaxSpeakingBank;return bank?.topics||[]}
function maxWritePracticeExample(entry,topic,i=0){const q='“'+entry.term+'”';const t=topic||'IELTS';const arr=[`In a Task 2 discussion about ${t}, ${q} can make an argument more precise.`,`I would use ${q} when developing a clear paragraph about ${t}.`,`For a B2–C1 essay on ${t}, ${q} is useful when explaining a reason or result.`,`A strong body paragraph about ${t} can include ${q} when the idea fits naturally.`];return arr[i%arr.length]}
function renderMaxWrite(el){
 const topics=maxWriteData();if(!topics.length){el.innerHTML='<div class="empty-state">Writing topic bank yuklanmadi.</div>';return}
 ui.maxWriteTopic=Math.max(0,Math.min(topics.length-1,ui.maxWriteTopic||0));const topic=topics[ui.maxWriteTopic],cards=topic.entries.filter(e=>e.kind==='Writing');
 const seg=['#6c55de','#6aa5e7','#39aa9a','#a45dd9','#e8ad58'];const background=`conic-gradient(${topics.map((_,i)=>`${seg[i%seg.length]} ${i*12}deg ${(i+1)*12}deg`).join(',')})`;const rotation=ui.maxWriteWheel===null?0:(1080-(ui.maxWriteWheel*12+6));
 el.innerHTML=`<section class="wb-write-wheel"><div class="wb-write-wheel-head"><span class="wb-kicker">WRITING TOPIC PRACTICE</span><h2>Writing Topic barabani</h2><p>Topicni tasodifiy tanlang, keyin shu mavzudagi Writing collocationlarni ko‘ring va o‘yinlarda mustahkamlang.</p></div><div class="wb-write-wheel-body"><div class="wb-write-wheel-frame"><span class="wb-write-wheel-pointer"></span><div class="wb-write-wheel-disc" style="background:${background};transform:rotate(${rotation}deg)">${topics.map((_,i)=>`<span style="--angle:${i*12+6}deg">${String(i+1).padStart(2,'0')}</span>`).join('')}</div><div class="wb-write-wheel-hub">W</div></div><div class="wb-write-wheel-control"><strong>${ui.maxWriteWheel===null?'Baraban tayyor':`Tanlangan topic: ${esc(topics[ui.maxWriteWheel].title)}`}</strong><p>Barabanni aylantirib topic tanlang yoki pastdagi selector orqali istalgan mavzuni oching.</p><button class="wb-play-seven" data-writing-action="maxwrite-spin">🎯 Barabanni aylantirish</button>${ui.maxWriteWheel!==null?`<button class="wb-wheel-open" data-writing-action="maxwrite-open-wheel">Tanlangan topicni ochish →</button>`:''}</div></div></section><div class="wb-section-head"><div><span class="wb-kicker">WRITING TOPIC BANK · COLLOCATIONS</span><h2>Writing Topic Collocations</h2><p>IELTS Writing mavzulari uchun saralangan collocationlar va practice.</p></div></div><div class="wb-maxwrite-toolbar"><select id="wbMaxWriteTopic">${topics.map((t,i)=>`<option value="${i}" ${i===ui.maxWriteTopic?'selected':''}>${i+1}. ${esc(t.title)}</option>`).join('')}</select><button data-writing-action="maxwrite-games">▶ Shu topicni o‘yinlarda o‘rganish</button></div><div class="wb-maxwrite-grid">${cards.map((c,i)=>`<article><small>WRITING · ${esc(topic.title)} · ${String(i+1).padStart(2,'0')}</small><h3>${esc(c.term)}</h3><p><b>O‘zbekcha:</b> ${esc(c.uz)}</p><div class="wb-maxwrite-examples"><span>${esc(maxWritePracticeExample(c,topic.title,0))}</span><span>${esc(maxWritePracticeExample(c,topic.title,1))}</span></div></article>`).join('')}</div>`;
}
function checkExpression(){return true}
function grammarBank(){return ui.grammarTask==='book'?(data.bookGrammarTopics||[]):ui.grammarTask==='task1'?data.task1Structures:data.task2Structures}
const grammarSkills=[['QOIDA / USE','Qoidani tushunish'],['MISOLNI TANISH','To‘g‘ri misolni ajratish'],['GAP FILL','Bo‘shliqni to‘ldirish'],['SO‘Z TARTIBI','Gapni qayta tuzish'],['TRUE / FALSE','Qoidani tekshirish'],['TARJIMA','Uzbek → English'],['REWRITE','Structure bilan qayta yozish'],['COMBINE','Fikrlarni birlashtirish'],['ACADEMIC UPGRADE','Akademikroq qilish'],['O‘ZINGIZ YOZING','IELTS gap yaratish']];
function grammarDoneCount(s){return (s.exercises||[]).filter(ex=>progress.grammar[`v6:${s.id}:${ex.n}`]).length}
function grammarTypeInput(s,ex,gk,saved){
 if(ex.type==='mcq')return `<div class="wb-options wb-grammar-options">${(ex.options||[]).map(x=>`<label><input type="radio" name="grammar-${gk}" data-grammar-choice value="${esc(x)}" ${saved===x?'checked':''}> <span>${esc(x)}</span></label>`).join('')}</div>`;
 if(ex.type==='reorder')return `<div class="wb-reorder-hint">🧩 So‘zlarni ma’noli va grammatik to‘g‘ri gapga aylantiring.</div><textarea id="wbGrammarAnswer" placeholder="To‘liq gapni yozing…">${esc(saved)}</textarea>`;
 if(ex.type==='gap')return `<textarea id="wbGrammarAnswer" class="wb-short-answer" placeholder="Faqat tushib qolgan so‘z yoki iborani yozing…">${esc(saved)}</textarea>`;
 if(ex.type==='translate')return `<textarea id="wbGrammarAnswer" placeholder="Inglizcha tarjimangiz…">${esc(saved)}</textarea>`;
 return `<textarea id="wbGrammarAnswer" placeholder="Javobingizni yozing…">${esc(saved)}</textarea>`;
}
function grammarOverview(s,count,book){
 const done=grammarDoneCount(s),pct=count?Math.round(done*100/count):0;
 return `<article class="wb-grammar-overview"><div class="wb-grammar-meta"><span class="wb-badge">${book?'BOOK GRAMMAR':'IELTS STRUCTURE'} · B2–C1</span>${s.chapter?`<span class="wb-source-pill">Chapter ${s.chapter} · page ${s.page}</span>`:''}</div><h2>${esc(s.pattern||s.title)}</h2>
 <div class="wb-meaning-grid"><div><small>ENGLISH EXPLANATION</small><p>${esc(s.meaning)}</p></div><div><small>O‘ZBEKCHA TUSHUNTIRISH</small><p><b>${esc(s.uzMeaning||'')}</b></p></div></div>
 ${(s.whenEn||s.whenUz)?`<div class="wb-when-grid"><div><small>WHEN / HOW TO USE</small><p>${esc(s.whenEn||s.meaning||'')}</p></div><div><small>QACHON / QANDAY ISHLATILADI</small><p>${esc(s.whenUz||s.uzMeaning||'')}</p></div></div>`:''}
 <h4>3 ta IELTS example + o‘zbekcha tarjimasi</h4><div class="wb-example-grid">${(s.examples||[]).slice(0,3).map((x,j)=>`<div><b>${j+1}. ${esc(x.en)}</b><span>${esc(x.uz)}</span></div>`).join('')}</div>
 <div class="wb-practice-preview"><div class="wb-practice-progress"><strong>${done}/${count}</strong><span>bajarilgan · ${pct}%</span></div><div class="wb-skill-preview">${grammarSkills.map(([a,b],i)=>`<div><b>${i+1}. ${a}</b><span>${b}</span><em>3 ta</em></div>`).join('')}</div><button class="wb-start-30" data-writing-action="grammar-start" data-id="${esc(s.id)}">▶ 30 ta turli mashqni boshlash</button></div></article>`;
}
function renderGrammar(el){
 const bank=grammarBank(); if(!bank.length){el.innerHTML='<p>Grammar data topilmadi.</p>';return}
 if(!ui.grammarId||!bank.some(x=>x.id===ui.grammarId))ui.grammarId=bank[0].id;
 const s=bank.find(x=>x.id===ui.grammarId)||bank[0], count=s.exercises?.length||0, book=ui.grammarTask==='book';
 const title=book?`${bank.length} ta Grammar for IELTS Writing mavzusi`:ui.grammarTask==='task2'?'30 Task 2 structures':'20 Task 1 structures';
 const total=bank.reduce((a,x)=>a+(x.exercises?.length||0),0);
 const aside=`<aside class="wb-grammar-topics">${bank.map(x=>`<div class="wb-grammar-topic ${x.id===s.id?'active':''}"><button class="wb-topic-main" data-writing-action="grammar-open" data-id="${esc(x.id)}"><b>${esc(x.pattern||x.title)}</b><span>${esc(x.uzMeaning||x.meaning)}</span>${x.chapter?`<small>Chapter ${x.chapter} · p.${x.page}</small>`:''}</button><button class="wb-topic-practice" data-writing-action="grammar-start" data-id="${esc(x.id)}"><strong>30</strong><span>ta mashq</span></button></div>`).join('')}</aside>`;
 let main='';
 if(!ui.grammarPractice){main=grammarOverview(s,count,book)}else{
   const n=((ui.grammarN%count)+count)%count,ex=s.exercises[n],gk=`v6:${s.id}:${ex.n}`,saved=progress.grammarAnswers[gk]||'',done=grammarDoneCount(s),pct=count?Math.round(done*100/count):0,input=grammarTypeInput(s,ex,gk,saved),group=Math.floor(n/3);
   main=`<article class="wb-grammar-practice" data-grammar-key="${esc(gk)}"><div class="wb-practice-top"><button class="wb-back" data-writing-action="grammar-overview">← Mavzuga qaytish</button><div><b>${done}/${count}</b><span>${pct}%</span></div></div><div class="wb-progress"><i style="width:${pct}%"></i></div>
   <div class="wb-grammar-meta"><span class="wb-badge">${esc(ex.level||'B2–C1')} · ${esc(ex.skill||ex.type.toUpperCase())} · ${ex.n}/${count}</span>${s.chapter?`<span class="wb-source-pill">Chapter ${s.chapter} · page ${s.page}</span>`:''}</div><h3>${esc(s.pattern||s.title)}</h3>
   <details class="wb-grammar-review"><summary>📘 Qoidani va 3 ta misolni qayta ko‘rish</summary><div class="wb-meaning-grid"><div><small>ENGLISH</small><p>${esc(s.meaning)}</p></div><div><small>O‘ZBEKCHA</small><p>${esc(s.uzMeaning||'')}</p></div></div><div class="wb-example-grid">${(s.examples||[]).slice(0,3).map((x,j)=>`<div><b>${j+1}. ${esc(x.en)}</b><span>${esc(x.uz)}</span></div>`).join('')}</div></details>
   <div class="wb-drill-tabs">${grammarSkills.map(([a],i)=>`<button class="${i===group?'active':''}" data-writing-action="grammar-jump" data-index="${i*3}"><span>${i+1}</span>${a}<b>${i*3+1}–${i*3+3}</b></button>`).join('')}</div>
   <div class="wb-drill-card"><div class="wb-drill-head"><span>${esc(ex.skill||'MASHQ')}</span><b>${ex.n} / ${count}</b></div><div class="wb-drill-prompt">${esc(ex.prompt).replace(/\n/g,'<br>')}</div>${input}<div class="wb-feedback"></div></div>
   <div class="wb-actions"><button data-writing-action="grammar-prev">← Oldingi</button><button class="wb-check" data-writing-action="grammar-check">Tekshirish</button><button data-writing-action="grammar-next">Keyingi →</button></div></article>`;
 }
 el.innerHTML=`<div class="wb-section-head wb-grammar-head"><div><span class="wb-kicker">${book?'GRAMMAR FOR IELTS WRITING · DAVID S. WILLS':'SAMPLE ANSWERS → GRAMMAR'}</span><h2>${title}</h2><p>${total} ta mashq · har bir mavzuda alohida <b>30 ta mashq</b> · 10 xil practice turi · B2–C1.</p></div><div class="wb-segment"><button class="${ui.grammarTask==='book'?'active':''}" data-writing-action="grammar-task" data-task="book">📘 Grammar Book</button><button class="${ui.grammarTask==='task2'?'active':''}" data-writing-action="grammar-task" data-task="task2">Task 2</button><button class="${ui.grammarTask==='task1'?'active':''}" data-writing-action="grammar-task" data-task="task1">Task 1</button></div></div><div class="wb-grammar-layout">${aside}${main}</div>`;
}
function checkGrammar(){
 const bank=grammarBank(),s=bank.find(x=>x.id===ui.grammarId)||bank[0],count=s.exercises?.length||0,ex=s.exercises[((ui.grammarN%count)+count)%count],gk=`v6:${s.id}:${ex.n}`,art=document.querySelector(`[data-grammar-key="${CSS.escape(gk)}"]`);if(!art)return;
 let user=art.querySelector('[data-grammar-choice]:checked')?.value??document.getElementById('wbGrammarAnswer')?.value??'';progress.grammarAnswers[gk]=user;let ok=false,msg='';
 if(ex.type==='mcq'){ok=norm(user)===norm(ex.answer);msg=ok?'Qoidani/misolni to‘g‘ri tanladingiz.':'Variantlarni qoida va misollar bilan yana solishtiring.'}
 else if(ex.type==='own'){const wc=words(user).length,anchor=norm(ex.anchor||''),anchorOk=!anchor||norm(user).includes(anchor);ok=wc>=10&&anchorOk;msg=ok?'Gap hajmi va target structure talabi bajarildi. Model bilan uslubni solishtiring.':'Kamida 10 so‘zli IELTS-style gap yozing va target structure’ni aniq ishlating.'}
 else if(['rewrite','combine','improve'].includes(ex.type)){const target=norm(ex.model||ex.answer),u=norm(user),core=contentWords(target).slice(0,6),hit=core.filter(x=>u.includes(x)).length,anchor=norm(ex.anchor||''),anchorOk=!anchor||u.includes(anchor);ok=words(user).length>=7&&anchorOk&&(core.length<2||hit>=2);msg=ok?'Ma’no saqlangan va target grammar uchun yetarli signal bor.':'Ma’noni saqlang, target grammarni aniqroq ishlating va gapni to‘liq yozing.'}
 else if(ex.type==='translate'){const target=norm(ex.answer),u=norm(user),core=contentWords(target),hit=core.filter(x=>u.includes(x)).length;ok=u===target||(words(user).length>=5&&hit>=Math.max(2,Math.ceil(core.length*.55)));msg=ok?'Tarjima model ma’nosi va grammatik strukturaga yaqin.':'Asosiy ma’no, word order va target grammarga e’tibor bering.'}
 else {ok=norm(user)===norm(ex.answer);msg=ok?'Javob to‘g‘ri.':'So‘z tartibi va target grammarni qayta tekshiring.'}
 progress.grammar[gk]=ok;const fb=art.querySelector('.wb-feedback');fb.className=`wb-feedback ${ok?'ok':'no'}`;fb.innerHTML=`<strong>${ok?'✓ To‘g‘ri':'↻ Qayta urinib ko‘ring'}</strong><p>${esc(msg)}</p>${(!ok||['own','rewrite','combine','improve','translate'].includes(ex.type))?modelPanel('Model / tavsiya etilgan javob',`<p>${esc(ex.model||ex.answer||'')}</p>`):''}`;save();
 const top=art.querySelector('.wb-practice-top div');if(top){const d=grammarDoneCount(s),p=count?Math.round(d*100/count):0;top.innerHTML=`<b>${d}/${count}</b><span>${p}%</span>`;const bar=art.querySelector('.wb-progress i');if(bar)bar.style.width=p+'%'}
}
function mockPrompt(task=ui.mockTask){const bank=data.mock[task]||[],idx=(ui.mockIndex%Math.max(1,bank.length)+bank.length)%bank.length;return bank[idx]}
function benchmarkFor(task,p){if(!p)return null;return sampleById(p.id)||data.samples.find(s=>s.task===task&&norm(s.prompt)===norm(p.prompt))||data.samples.find(s=>s.task===task&&s.band)}
function benchmarkHtml(task,p){const b=benchmarkFor(task,p);if(!b)return'';const cs=data.criteria[task];return `<details class="wb-benchmark"><summary>Band 9 / high-level model + 4 criteria analysis</summary><div class="wb-benchmark-head"><b>${esc(b.title)}</b><span>${esc(b.source)}${b.band?` · Band ${esc(b.band)}`:''}</span></div><div class="wb-score-grid">${cs.map(c=>`<article><span>${esc(c)}</span><strong>${b.band?'≈ 9':'High'}</strong><p>${benchmarkReason(c,b)}</p></article>`).join('')}</div><div class="wb-full-answer">${sentenceParagraphs(b.answer).map(x=>`<p>${esc(x)}</p>`).join('')}</div></details>`}
function benchmarkReason(c,b){if(c.includes('Task'))return `Clear ${b.task==='task1'?'overview/key features':'position'} va relevant development.`;if(c.includes('Coherence'))return 'Paragraph progression, referencing va linkingni kuzating.';if(c.includes('Lexical'))return 'Topic-specific vocabulary, collocation va precise wordingni kuzating.';return 'Simple + complex structures, accuracy va sentence controlni kuzating.'}
function criteriaHelp(c){if(c.includes('Task'))return 'Savolning barcha qismlariga javob, clear position/overview, relevant va rivojlantirilgan ideas/key features.';if(c.includes('Coherence'))return 'Logical progression, paragraphing, referencing va cohesive devices.';if(c.includes('Lexical'))return 'Range, precision, collocation, spelling va keraksiz repetition.';return 'Simple + complex structures, sentence control, grammar va punctuation accuracy.'}
function renderMock(el){if(ui.mockTask==='full'){const p1=mockPrompt('task1'),p2=mockPrompt('task2');el.innerHTML=`<div class="wb-section-head"><div><span class="wb-kicker">FULL ACADEMIC EXAM MODE</span><h2>Writing Mock · 60 minutes</h2><p>Task 1 · 20 min, Task 2 · 40 min tavsiya.</p></div><div class="wb-segment"><button class="active" data-writing-action="mock-task" data-task="full">Full 60</button><button data-writing-action="mock-task" data-task="task1">Task 1</button><button data-writing-action="mock-task" data-task="task2">Task 2</button></div></div><article class="wb-mock"><div class="wb-mock-top"><span>ACADEMIC FULL MOCK</span><strong id="wbMockTimer">60:00</strong></div><section class="wb-mock-task"><span class="wb-badge">TASK 1</span><h3>${esc(p1.title)}</h3><div class="wb-prompt">${esc(p1.prompt)}</div><textarea id="wbMockEssay1" spellcheck="false"></textarea><span id="wbWordCount1">0 words</span></section><section class="wb-mock-task"><span class="wb-badge">TASK 2</span><h3>${esc(p2.title)}</h3><div class="wb-prompt">${esc(p2.prompt)}</div><textarea id="wbMockEssay2" spellcheck="false"></textarea><span id="wbWordCount2">0 words</span></section><div class="wb-mock-meta"><button data-writing-action="mock-random">Boshqa savol</button><button data-writing-action="mock-start">Timer start</button><button class="primary" data-writing-action="mock-submit">Submit & 4 criteria</button></div><div id="wbMockResult"></div></article>${benchmarkHtml('task1',p1)}${benchmarkHtml('task2',p2)}`;return}const p=mockPrompt();el.innerHTML=`<div class="wb-section-head"><div><span class="wb-kicker">IELTS WRITING EXAM MODE</span><h2>${ui.mockTask==='task1'?'Task 1 · 20 min':'Task 2 · 40 min'}</h2><p>Model/ideas yozish paytida ko‘rinmaydi.</p></div><div class="wb-segment"><button data-writing-action="mock-task" data-task="full">Full 60</button><button class="${ui.mockTask==='task1'?'active':''}" data-writing-action="mock-task" data-task="task1">Task 1</button><button class="${ui.mockTask==='task2'?'active':''}" data-writing-action="mock-task" data-task="task2">Task 2</button></div></div><article class="wb-mock"><div class="wb-mock-top"><span>${esc(p.source)}</span><strong id="wbMockTimer">${ui.mockTask==='task1'?'20:00':'40:00'}</strong></div><h3>${esc(p.title)}</h3><div class="wb-prompt">${esc(p.prompt)}</div><textarea id="wbMockEssay" spellcheck="false"></textarea><span id="wbWordCount">0 words</span><div class="wb-mock-meta"><button data-writing-action="mock-random">Boshqa savol</button><button data-writing-action="mock-start">Timer start</button><button class="primary" data-writing-action="mock-submit">Submit & 4 criteria</button></div><div id="wbMockResult"></div></article><div class="wb-criteria-info"><h3>Baholash mezonlari</h3><div>${data.criteria[ui.mockTask].map((c,i)=>`<article><b>${i+1}. ${esc(c)}</b><p>${criteriaHelp(c)}</p></article>`).join('')}</div></div>${benchmarkHtml(ui.mockTask,p)}`}
function scoreEssay(text,task,prompt){const ws=(text.match(/[A-Za-zÀ-ÿ']+/g)||[]),wc=ws.length,lower=ws.map(x=>x.toLowerCase()),uniq=new Set(lower),paras=text.trim().split(/\n\s*\n/).filter(Boolean),sents=text.split(/[.!?]+/).map(x=>x.trim()).filter(Boolean),target=task==='task1'?150:250,promptKeys=[...new Set((prompt.match(/[A-Za-z]{5,}/g)||[]).map(x=>x.toLowerCase()))].slice(0,20),coverage=promptKeys.length?promptKeys.filter(k=>lower.includes(k)).length/promptKeys.length:0,conn=(text.match(/\b(however|therefore|moreover|furthermore|whereas|while|although|overall|in conclusion|by contrast|for example|as a result|on the other hand|firstly|secondly)\b/gi)||[]).length,complex=(text.match(/\b(although|while|whereas|which|who|because|if|when|despite|in spite of|whether)\b/gi)||[]).length,long=ws.filter(w=>w.length>=9).length,ttr=wc?uniq.size/wc:0,round=x=>Math.max(4,Math.min(9,Math.round(x*2)/2));let ta=round(5+Math.min(1,wc/target)*1.8+Math.min(.5,coverage)*1.5+(paras.length>=3?.7:0)),cc=round(5+(paras.length>=4?1:paras.length>=3?.6:0)+Math.min(1.5,conn/6)),lr=round(5+Math.min(1.5,ttr*2)+Math.min(1.5,long/20)),gra=round(5+Math.min(1.4,complex/6)+(sents.length&&sents.filter(x=>x.split(/\s+/).length>=15).length/sents.length>.3?.7:0));if(wc<target*.7){ta-=1;cc-=.5;lr-=.5;gra-=.5}return[ta,cc,lr,gra].map(round)}
function resultHtml(scores,task){const cs=data.criteria[task],overall=Math.round((scores.reduce((a,b)=>a+b,0)/4)*2)/2;return `<div class="wb-result"><h3>Estimated practice score: ${overall.toFixed(1)}</h3><p class="wb-disclaimer">Local practice estimate — rasmiy IELTS examiner bahosi emas.</p><div class="wb-score-grid">${scores.map((s,i)=>`<article><span>${esc(cs[i])}</span><strong>${s.toFixed(1)}</strong><p>${feedbackCriterion(cs[i],s)}</p></article>`).join('')}</div></div>`}
function feedbackCriterion(c,s){if(c.includes('Task'))return s>=7?'Position/overview va development yaxshi.':'Barcha qismlarni qamrab olib, position/overview va supportni kengaytiring.';if(c.includes('Coherence'))return s>=7?'Progression va paragraphing yaxshi.':'Har paragraphga bitta central idea va tabiiy linking bering.';if(c.includes('Lexical'))return s>=7?'Range yaxshi; collocation va precisionni saqlang.':'Takrorni kamaytirib, topic-specific collocation ishlating.';return s>=7?'Complex structures bor; accuracyga e’tibor bering.':'Simple + complex gaplarni aralashtirib, verb/article/punctuationni tekshiring.'}
function startTimer(){stopTimer();ui.mockLeft=(ui.mockTask==='full'?60:ui.mockTask==='task1'?20:40)*60;const tick=()=>{const el=document.getElementById('wbMockTimer');if(el)el.textContent=`${String(Math.floor(ui.mockLeft/60)).padStart(2,'0')}:${String(ui.mockLeft%60).padStart(2,'0')}`;if(ui.mockLeft<=0)stopTimer();else ui.mockLeft--};tick();ui.mockTimer=setInterval(tick,1000)}
function stopTimer(){if(ui.mockTimer)clearInterval(ui.mockTimer);ui.mockTimer=null}
function submitMock(){if(ui.mockTask==='full'){const t1=document.getElementById('wbMockEssay1')?.value||'',t2=document.getElementById('wbMockEssay2')?.value||'',p1=mockPrompt('task1'),p2=mockPrompt('task2'),s1=scoreEssay(t1,'task1',p1.prompt),s2=scoreEssay(t2,'task2',p2.prompt),o1=s1.reduce((x,y)=>x+y,0)/4,o2=s2.reduce((x,y)=>x+y,0)/4,overall=Math.round(((o1+2*o2)/3)*2)/2;document.getElementById('wbMockResult').innerHTML=`<div class="wb-result"><h3>Full Writing estimated band: ${overall.toFixed(1)}</h3>${resultHtml(s1,'task1')}${resultHtml(s2,'task2')}</div>`;progress.mockHistory.push({at:new Date().toISOString(),task:'full',scores1:s1,scores2:s2,overall})}else{const ta=document.getElementById('wbMockEssay'),p=mockPrompt(),scores=scoreEssay(ta.value,ui.mockTask,p.prompt);document.getElementById('wbMockResult').innerHTML=resultHtml(scores,ui.mockTask);progress.mockHistory.push({at:new Date().toISOString(),task:ui.mockTask,promptId:p.id,scores})}progress.mockHistory=progress.mockHistory.slice(-100);window.VividHistoryRecord?.('Writing Mock',ui.mockTask==='full'?'Full Writing Mock tugadi':`${ui.mockTask.toUpperCase()} Writing Mock tugadi`,ui.mockTask==='full'?'Task 1 + Task 2 topshirildi':'Essay topshirildi',{task:ui.mockTask});save()}
function onClick(b){const a=b.dataset.writingAction;if(!a)return;
 if(a==='tab'){ui.tab=b.dataset.tab;ui.sampleId=null;renderBody()}
 else if(a==='day-prev'||a==='day-next'){ui.day=clamp(ui.day+(a==='day-next'?1:-1),1,50);renderCourse(document.getElementById('wbBody'))}
 else if(a==='exercise'){ui.exercise=b.dataset.exercise;renderCourse(document.getElementById('wbBody'))}
 else if(a==='check-course')checkCourse(Number(b.dataset.day),b.dataset.type,Number(b.dataset.index))
 else if(a==='paint-role'){ui.paintRole=b.dataset.role;document.querySelectorAll('.wb-paint').forEach(x=>x.classList.toggle('active',x.dataset.role===ui.paintRole))}
 else if(a==='paint-pending'){const p=window.__wbPendingPaint;if(p?.spans?.length){for(const sp of p.spans){applyRoleToSpan(sp,b.dataset.role);sp.classList.remove('pending-paint')}const box=p.essay?.parentElement?.querySelector('.wb-floating-palette');if(box)box.classList.remove('show');window.__wbPendingPaint=null}}
 else if(a==='paint-check'){const s=sampleById(b.dataset.id),box=b.closest('.wb-sample-detail')||b.closest('.wb-task');checkPaintedEssay(box,s);save()}
 else if(a==='paint-clear'){const s=sampleById(b.dataset.id);progress.sampleTags[s.id]={};save();renderSampleDetail(document.getElementById('wbBody'),s)}
 else if(a==='open-sample'){ui.tab='samples';ui.sampleId=b.dataset.id;document.querySelectorAll('.wb-tabs button').forEach(x=>x.classList.toggle('active',x.dataset.tab==='samples'));renderBody()}
 else if(a==='sample-back'){ui.sampleId=null;renderSamples(document.getElementById('wbBody'))}
 else if(a==='sample-prev'||a==='sample-next'){ui.samplePage+=a==='sample-next'?1:-1;renderSamples(document.getElementById('wbBody'))}
 else if(a==='maxwrite-spin'){const topics=maxWriteData();ui.maxWriteWheel=Math.floor(Math.random()*topics.length);renderMaxWrite(document.getElementById('wbBody'))}
 else if(a==='maxwrite-open-wheel'){if(ui.maxWriteWheel!==null){ui.maxWriteTopic=ui.maxWriteWheel;renderMaxWrite(document.getElementById('wbBody'))}}
 else if(a==='maxwrite-games'){const topic=maxWriteData()[ui.maxWriteTopic],cards=(topic?.entries||[]).filter(e=>e.kind==='Writing').map((e,i)=>({id:`mw:${topic.id}:${i}`,term:e.term,uz:e.uz,example:maxWritePracticeExample(e,topic.title,2)}));if(cards.length&&window.openWritingGames)window.openWritingGames(cards,topic.title)}
 else if(a==='colloc-topic'){ui.collocTopic=Number(b.dataset.index);renderExpressions(document.getElementById('wbBody'))}
 else if(a==='colloc-flip'){const id=b.dataset.id;ui.collocFlip[id]=!ui.collocFlip[id];renderExpressions(document.getElementById('wbBody'))}
 else if(a==='colloc-known'){const id=b.dataset.id;progress.collocationKnown[id]=!progress.collocationKnown[id];save();renderExpressions(document.getElementById('wbBody'))}
 else if(a==='colloc-games'){const t=(data.collocationTopics||[])[ui.collocTopic];if(t?.cards?.length&&window.openWritingGames)window.openWritingGames(t.cards,t.topic);else alert('7 o‘yin moduli hali tayyor emas.')}
 else if(a==='grammar-task'){ui.grammarTask=b.dataset.task;ui.grammarId=null;ui.grammarN=0;ui.grammarPractice=false;renderGrammar(document.getElementById('wbBody'))}
 else if(a==='grammar-open'){ui.grammarId=b.dataset.id;ui.grammarN=0;ui.grammarPractice=false;renderGrammar(document.getElementById('wbBody'))}
 else if(a==='grammar-start'){ui.grammarId=b.dataset.id||ui.grammarId;ui.grammarN=0;ui.grammarPractice=true;renderGrammar(document.getElementById('wbBody'))}
 else if(a==='grammar-overview'){ui.grammarPractice=false;renderGrammar(document.getElementById('wbBody'))}
 else if(a==='grammar-jump'){ui.grammarN=Number(b.dataset.index)||0;ui.grammarPractice=true;renderGrammar(document.getElementById('wbBody'))}
 else if(a==='grammar-prev'||a==='grammar-next'){const bank=grammarBank(),s=bank.find(x=>x.id===ui.grammarId)||bank[0],n=s?.exercises?.length||1;ui.grammarN=(ui.grammarN+(a==='grammar-next'?1:-1)+n)%n;renderGrammar(document.getElementById('wbBody'))}
 else if(a==='grammar-check')checkGrammar()
 else if(a==='mock-task'){ui.mockTask=b.dataset.task;ui.mockIndex=0;stopTimer();renderMock(document.getElementById('wbBody'))}
 else if(a==='mock-random'){ui.mockIndex++;stopTimer();renderMock(document.getElementById('wbBody'))}
 else if(a==='mock-start')startTimer()
 else if(a==='mock-submit')submitMock()
}
function onInput(t){if(t.matches('[data-writing-note]')){progress.notes[t.dataset.writingNote]=t.value.slice(0,12000);clearTimeout(t._sv);t._sv=setTimeout(save,250);return}if(t.id==='wbSampleQuery'){ui.sampleQuery=t.value;ui.samplePage=0;renderSamples(document.getElementById('wbBody'));document.getElementById('wbSampleQuery')?.focus();return}if(t.id==='wbExprAnswer'){const id=document.querySelector('.wb-expression-game')?.dataset.exprId;if(id){progress.expressionAnswers[id]=t.value;save()}return}if(t.id==='wbGrammarAnswer'){const art=t.closest('[data-grammar-key]');if(art){progress.grammarAnswers[art.dataset.grammarKey]=t.value;save()}return}if(t.id==='wbMockEssay'||t.id==='wbMockEssay1'||t.id==='wbMockEssay2'){const map={wbMockEssay:'wbWordCount',wbMockEssay1:'wbWordCount1',wbMockEssay2:'wbWordCount2'},c=document.getElementById(map[t.id]);if(c)c.textContent=`${(t.value.match(/\S+/g)||[]).length} words`}}
function onChange(t){if(t.id==='wbMaxWriteTopic'){ui.maxWriteTopic=Number(t.value);renderMaxWrite(document.getElementById('wbBody'))}else if(t.id==='wbLizTopic'){ui.ideaIndex=Number(t.value);renderIdeas(document.getElementById('wbBody'))}else if(t.id==='wbSampleTask'){ui.sampleTask=t.value;ui.samplePage=0;renderSamples(document.getElementById('wbBody'))}else if(t.id==='wbSampleSource'){ui.sampleSource=t.value;ui.samplePage=0;renderSamples(document.getElementById('wbBody'))}else if(t.matches('[data-expr-choice]')){const id=t.closest('.wb-expression-game')?.dataset.exprId;if(id){progress.expressionAnswers[id]=t.value;save()}}else if(t.matches('[data-grammar-choice]')){const art=t.closest('[data-grammar-key]');if(art){progress.grammarAnswers[art.dataset.grammarKey]=t.value;save()}}}
document.addEventListener('click',e=>{const sentence=e.target.closest('.wb-paint-sentence');if(sentence&&!window.getSelection()?.toString()){applyRoleToSpan(sentence,ui.paintRole);return}const b=e.target.closest('[data-writing-action]');if(b)onClick(b)});
document.addEventListener('mouseup',e=>{const essay=e.target.closest?.('.wb-highlight-essay');if(essay)setTimeout(()=>applySelection(essay),0)});
document.addEventListener('input',e=>onInput(e.target));document.addEventListener('change',e=>onChange(e.target));window.addEventListener('beforeunload',stopTimer);
window.WritingBoost={render,getProgress,setProgress,save};
})();
